import { apiRequestAuth, toPagedResult } from '../../../lib/apiClient.js'

const EMPTY_GUID = '00000000-0000-0000-0000-000000000000'

function toArray(value) {
  return Array.isArray(value) ? value : []
}

function trimOrNull(value) {
  const text = String(value ?? '').trim()
  return text || null
}

function numberOrNull(value) {
  if (value === null || value === undefined || value === '') return null
  const number = Number(value)
  return Number.isFinite(number) ? number : null
}

export function mapProductImage(item) {
  if (!item || typeof item !== 'object') return null
  return {
    id: item.id ?? item.Id,
    productId: item.productId ?? item.ProductId,
    imageUrl: item.imageUrl ?? item.ImageUrl ?? '',
    altText: item.altText ?? item.AltText ?? '',
    sortOrder: Number(item.sortOrder ?? item.SortOrder ?? 0),
    isThumbnail: Boolean(item.isThumbnail ?? item.IsThumbnail ?? false),
  }
}

export function mapProductUnit(item) {
  if (!item || typeof item !== 'object') return null
  return {
    id: item.id ?? item.Id,
    productId: item.productId ?? item.ProductId,
    variantId: item.variantId ?? item.VariantId ?? null,
    unitName: item.unitName ?? item.UnitName ?? '',
    conversionRate: Number(item.conversionRate ?? item.ConversionRate ?? 1),
    price: numberOrNull(item.price ?? item.Price),
    barcode: item.barcode ?? item.Barcode ?? '',
    isDirectSell: Boolean(item.isDirectSell ?? item.IsDirectSell ?? true),
    isBaseUnit: Boolean(item.isBaseUnit ?? item.IsBaseUnit ?? false),
  }
}

export function mapProductVariant(item) {
  if (!item || typeof item !== 'object') return null
  const rawUnits = item.units ?? item.Units ?? []
  const rawBomLines = item.bomLines ?? item.BomLines ?? []
  const bomLineCount = Number(item.bomLineCount ?? item.BomLineCount ?? rawBomLines.length ?? 0)
  return {
    id: item.id ?? item.Id,
    productId: item.productId ?? item.ProductId,
    skuCode: item.skuCode ?? item.SkuCode ?? '',
    barcode: item.barcode ?? item.Barcode ?? '',
    variantName: item.variantName ?? item.VariantName ?? '',
    optionValuesJson: item.optionValuesJson ?? item.OptionValuesJson ?? '{}',
    costPrice: Number(item.costPrice ?? item.CostPrice ?? 0),
    retailPrice: Number(item.retailPrice ?? item.RetailPrice ?? 0),
    minStock: numberOrNull(item.minStock ?? item.MinStock),
    maxStock: numberOrNull(item.maxStock ?? item.MaxStock),
    priceBeforeTax: numberOrNull(item.priceBeforeTax ?? item.PriceBeforeTax),
    salesTaxPercent: numberOrNull(item.salesTaxPercent ?? item.SalesTaxPercent ?? item.taxPercent ?? item.TaxPercent),
    salesTaxMode: item.salesTaxMode ?? item.SalesTaxMode ?? '',
    isSellable: Boolean(item.isSellable ?? item.IsSellable ?? true),
    allowRewardPoints: Boolean(item.allowRewardPoints ?? item.AllowRewardPoints ?? true),
    isActive: Boolean(item.isActive ?? item.IsActive ?? true),
    imageUrl: item.imageUrl ?? item.ImageUrl ?? '',
    unitName: item.unitName ?? item.UnitName ?? '',
    conversionRate: Number(item.conversionRate ?? item.ConversionRate ?? 1),
    baseVariantId: item.baseVariantId ?? item.BaseVariantId ?? null,
    isBaseUnitVariant: Boolean(item.isBaseUnitVariant ?? item.IsBaseUnitVariant ?? false),
    isAutoGeneratedSku: Boolean(item.isAutoGeneratedSku ?? item.IsAutoGeneratedSku ?? false),
    isPurchasable: Boolean(item.isPurchasable ?? item.IsPurchasable),
    canBeBomComponent: Boolean(item.canBeBomComponent ?? item.CanBeBomComponent),
    canUseInCustom: Boolean(item.canUseInCustom ?? item.CanUseInCustom),
    canHaveBom: Boolean(item.canHaveBom ?? item.CanHaveBom),
    hasBom: Boolean(item.hasBom ?? item.HasBom ?? bomLineCount > 0),
    bomLineCount,
    units: toArray(rawUnits).map(mapProductUnit).filter(Boolean),
    bomLines: toArray(rawBomLines).map((line) => {
      const materialUnitName =
        line.materialUnitName ?? line.MaterialUnitName ?? line.materialUnit ?? line.MaterialUnit ?? line.baseUnit ?? line.BaseUnit ?? ''
      return {
        materialId: line.materialId ?? line.MaterialId,
        materialName: line.materialName ?? line.MaterialName ?? '',
        materialUnitName,
        baseUnit: materialUnitName,
        quantity: Number(line.quantity ?? line.Quantity ?? 0),
        componentUnitCost: numberOrNull(line.componentUnitCost ?? line.ComponentUnitCost),
        componentVariantId: line.componentVariantId ?? line.ComponentVariantId ?? null,
        componentSkuCode: line.componentSkuCode ?? line.ComponentSkuCode ?? '',
        componentVariantName: line.componentVariantName ?? line.ComponentVariantName ?? '',
        isRequiredBaseComponent: Boolean(line.isRequiredBaseComponent ?? line.IsRequiredBaseComponent ?? false),
      }
    }),
  }
}

export function mapProductSku(item) {
  if (!item || typeof item !== 'object') return null
  return {
    id: item.id ?? item.Id,
    productId: item.productId ?? item.ProductId,
    productName: item.productName ?? item.ProductName ?? '',
    categoryId: item.categoryId ?? item.CategoryId ?? null,
    categoryName: item.categoryName ?? item.CategoryName ?? '',
    skuCode: item.skuCode ?? item.SkuCode ?? '',
    barcode: item.barcode ?? item.Barcode ?? '',
    // packagingType is now VariantName — keep packagingType field for compatibility
    packagingType: item.packagingType ?? item.PackagingType ?? item.variantName ?? item.VariantName ?? '',
    variantName: item.variantName ?? item.VariantName ?? item.packagingType ?? item.PackagingType ?? '',
    weightInGrams: Number(item.weightInGrams ?? item.WeightInGrams ?? 0),
    // basePrice is now RetailPrice — keep basePrice field for compatibility
    basePrice: Number(item.basePrice ?? item.BasePrice ?? item.retailPrice ?? item.RetailPrice ?? 0),
    costPrice: Number(item.costPrice ?? item.CostPrice ?? item.basePrice ?? item.BasePrice ?? 0),
    retailPrice: Number(item.retailPrice ?? item.RetailPrice ?? item.basePrice ?? item.BasePrice ?? 0),
    minStock: numberOrNull(item.minStock ?? item.MinStock),
    maxStock: numberOrNull(item.maxStock ?? item.MaxStock),
    isSellable: Boolean(item.isSellable ?? item.IsSellable ?? true),
    allowRewardPoints: Boolean(item.allowRewardPoints ?? item.AllowRewardPoints ?? true),
    imageUrl: item.imageUrl ?? item.ImageUrl ?? '',
    isActive: Boolean(item.isActive ?? item.IsActive ?? true),
    createdAt: item.createdAt ?? item.CreatedAt ?? null,
    syncedToStoreAt: item.syncedToStoreAt ?? item.SyncedToStoreAt ?? null,
    unitName: item.unitName ?? item.UnitName ?? '',
    conversionRate: Number(item.conversionRate ?? item.ConversionRate ?? 1),
    baseVariantId: item.baseVariantId ?? item.BaseVariantId ?? null,
    isBaseUnitVariant: Boolean(item.isBaseUnitVariant ?? item.IsBaseUnitVariant ?? false),
    isAutoGeneratedSku: Boolean(item.isAutoGeneratedSku ?? item.IsAutoGeneratedSku ?? false),
    isPurchasable: Boolean(item.isPurchasable ?? item.IsPurchasable),
    canBeBomComponent: Boolean(item.canBeBomComponent ?? item.CanBeBomComponent),
    canUseInCustom: Boolean(item.canUseInCustom ?? item.CanUseInCustom),
    canHaveBom: Boolean(item.canHaveBom ?? item.CanHaveBom),
    productType: item.productType ?? item.ProductType ?? '',
    inventoryUnit: item.inventoryUnit ?? item.InventoryUnit ?? '',
    priceUnit:
      item.priceUnit
      ?? item.PriceUnit
      ?? item.inventoryUnit
      ?? item.InventoryUnit
      ?? '',
  }
}

const SUPPLIER_RECEIPT_PRODUCT_TYPES = new Set(['THANH_PHAM', 'NGUYEN_LIEU', 'BAO_BI'])

function normalizeCatalogBoolean(value) {
  if (value === true || value === 1) return true
  if (typeof value === 'string') {
    const normalized = value.trim().toLowerCase()
    return normalized === 'true' || normalized === '1'
  }
  return false
}

export function normalizeSupplierReceiptProductType(value) {
  if (typeof value !== 'string') return null
  const productType = value.trim().toUpperCase()
  return SUPPLIER_RECEIPT_PRODUCT_TYPES.has(productType) ? productType : null
}

export function isSupplierReceiptEligibleSku(sku) {
  return sku?.isActive === true
    && sku?.isPurchasable === true
    && normalizeSupplierReceiptProductType(sku.productType) !== null
}

export function mapSupplierReceiptSku(item) {
  if (!item || typeof item !== 'object') return null
  const id = item.skuId ?? item.SkuId ?? item.variantId ?? item.VariantId ?? null
  if (!id) return null

  const skuCode = item.skuCode ?? item.SkuCode ?? ''
  const variantName = item.variantName ?? item.VariantName ?? ''
  const productName = item.productName ?? item.ProductName ?? item.displayName ?? item.DisplayName ?? item.skuName ?? item.SkuName ?? variantName ?? skuCode
  const productType = normalizeSupplierReceiptProductType(item.productType ?? item.ProductType)

  return {
    id,
    skuId: id,
    variantId: id,
    productId: item.productId ?? item.ProductId ?? null,
    productName,
    displayName: productName,
    skuCode,
    packagingType: variantName,
    variantName,
    unitName: item.unitName ?? item.UnitName ?? '',
    inventoryUnit: item.inventoryUnit ?? item.InventoryUnit ?? '',
    productType: productType ?? '',
    isActive: normalizeCatalogBoolean(item.isActive ?? item.IsActive),
    isPurchasable: normalizeCatalogBoolean(item.isPurchasable ?? item.IsPurchasable),
  }
}

export function mapProduct(item) {
  if (!item || typeof item !== 'object') return null
  const rawSkus = item.skus ?? item.Skus ?? []
  const rawImages = item.images ?? item.Images ?? []
  const rawUnits = item.units ?? item.Units ?? []
  const rawVariants = item.variants ?? item.Variants ?? []
  const rawAttributes = item.attributes ?? item.Attributes ?? []
  return {
    id: item.id ?? item.Id,
    categoryId: item.categoryId ?? item.CategoryId,
    categoryName: item.categoryName ?? item.CategoryName ?? '',
    name: item.name ?? item.Name ?? '',
    origin: item.origin ?? item.Origin ?? '',
    flavorProfile: item.flavorProfile ?? item.FlavorProfile ?? '',
    brewingGuide: item.brewingGuide ?? item.BrewingGuide ?? '',
    description: item.description ?? item.Description ?? '',
    baseUnit: item.baseUnit ?? item.BaseUnit ?? 'unit',
    inventoryUnit: item.inventoryUnit ?? item.InventoryUnit ?? 'Piece',
    weightValue: numberOrNull(item.weightValue ?? item.WeightValue),
    weightUnit: item.weightUnit ?? item.WeightUnit ?? '',
    isVariantParent: Boolean(item.isVariantParent ?? item.IsVariantParent ?? false),
    isActive: Boolean(item.isActive ?? item.IsActive ?? true),
    isDeleted: Boolean(item.isDeleted ?? item.IsDeleted ?? false),
    createdAt: item.createdAt ?? item.CreatedAt ?? null,
    syncedToStoreAt: item.syncedToStoreAt ?? item.SyncedToStoreAt ?? null,
    productType: item.productType ?? item.ProductType ?? 'THANH_PHAM',
    skus: toArray(rawSkus).map(mapProductSku).filter(Boolean),
    images: toArray(rawImages).map(mapProductImage).filter(Boolean).sort((a, b) => a.sortOrder - b.sortOrder),
    units: toArray(rawUnits).map(mapProductUnit).filter(Boolean),
    variants: toArray(rawVariants).map(mapProductVariant).filter(Boolean),
    attributes: toArray(rawAttributes)
      .map((attribute) => ({
        id: attribute.id ?? attribute.Id,
        productId: attribute.productId ?? attribute.ProductId,
        attributeNameId: attribute.attributeNameId ?? attribute.AttributeNameId ?? null,
        attributeName: attribute.attributeName ?? attribute.AttributeName ?? '',
        value: attribute.value ?? attribute.Value ?? '',
      }))
      .filter((attribute) => attribute.attributeName || attribute.value),
  }
}

function buildProductQuery(params = {}) {
  const search = new URLSearchParams()
  if (params.search) search.set('search', params.search)
  if (params.categoryId) search.set('categoryId', String(params.categoryId))
  if (params.isActive === true || params.isActive === false) search.set('isActive', String(params.isActive))
  if (params.isDeleted === true) search.set('isDeleted', 'true')
  if (params.productType) search.set('productType', String(params.productType))
  search.set('page', String(params.page ?? 1))
  search.set('pageSize', String(Math.min(100, Math.max(1, params.pageSize ?? 20))))
  return search.toString()
}

export async function fetchProducts(params = {}) {
  const query = buildProductQuery(params)
  const data = await apiRequestAuth(`/api/v1/products?${query}`, { method: 'GET' })
  const paged = toPagedResult(data)
  return {
    ...paged,
    items: paged.items.map(mapProduct).filter(Boolean),
    totalPages: Number(data?.totalPages ?? data?.TotalPages ?? (Math.ceil(paged.totalCount / paged.pageSize) || 1)),
  }
}

/** Danh sách hàng hóa cho Admin/Manager — gọi endpoint riêng, luôn trả catalog cửa hàng. */
export async function fetchStoreProducts(params = {}) {
  const query = buildProductQuery(params)
  const data = await apiRequestAuth(`/api/v1/store/products?${query}`, { method: 'GET' })
  const paged = toPagedResult(data)
  return {
    ...paged,
    items: paged.items.map(mapProduct).filter(Boolean),
    totalPages: Number(data?.totalPages ?? data?.TotalPages ?? (Math.ceil(paged.totalCount / paged.pageSize) || 1)),
  }
}

export async function fetchProductById(id) {
  const data = await apiRequestAuth(`/api/v1/products/${id}`, { method: 'GET' })
  return mapProduct(data)
}

/** Chi tiết sản phẩm cho Admin/Manager/Sale — catalog cửa hàng. */
export async function fetchStoreProductById(id) {
  const data = await apiRequestAuth(`/api/v1/store/products/${id}`, { method: 'GET' })
  return mapProduct(data)
}

function buildImageBody(image, index) {
  return {
    imageUrl: trimOrNull(image.imageUrl) || '',
    altText: trimOrNull(image.altText),
    sortOrder: Number.isFinite(Number(image.sortOrder)) ? Number(image.sortOrder) : index,
    isThumbnail: Boolean(image.isThumbnail),
  }
}

function buildUnitBody(unit) {
  return {
    variantId: unit.variantId || null,
    unitName: trimOrNull(unit.unitName) || '',
    conversionRate: Number(unit.conversionRate || 1),
    price: numberOrNull(unit.price),
    barcode: trimOrNull(unit.barcode),
    isDirectSell: Boolean(unit.isDirectSell),
    isBaseUnit: Boolean(unit.isBaseUnit),
  }
}

function buildVariantBody(variant) {
  return {
    skuCode: String(variant.skuCode || '').trim().toUpperCase(),
    requestSkuKey: trimOrNull(variant.requestSkuKey),
    barcode: trimOrNull(variant.barcode),
    variantName: trimOrNull(variant.variantName) || '',
    optionValuesJson: trimOrNull(variant.optionValuesJson) || '{}',
    costPrice: Number(variant.costPrice || 0),
    retailPrice: Number(variant.retailPrice || 0),
    minStock: numberOrNull(variant.minStock),
    maxStock: numberOrNull(variant.maxStock),
    isSellable: Boolean(variant.isSellable),
    allowRewardPoints: Boolean(variant.allowRewardPoints),
    isActive: variant.isActive !== false,
    imageUrl: trimOrNull(variant.imageUrl),
    units: toArray(variant.units).map(buildUnitBody),
    unitName: trimOrNull(variant.unitName),
    conversionRate: Number(variant.conversionRate || 1),
    baseVariantId: variant.baseVariantId || null,
    baseSkuCode: trimOrNull(variant.baseSkuCode),
    baseRequestSkuKey: trimOrNull(variant.baseRequestSkuKey),
    isBaseUnitVariant: Boolean(variant.isBaseUnitVariant),
    isAutoGeneratedSku: Boolean(variant.isAutoGeneratedSku),
    isPurchasable: typeof variant.isPurchasable === 'boolean' ? variant.isPurchasable : null,
    canBeBomComponent: typeof variant.canBeBomComponent === 'boolean' ? variant.canBeBomComponent : null,
    canUseInCustom: typeof variant.canUseInCustom === 'boolean' ? variant.canUseInCustom : null,
    canHaveBom: typeof variant.canHaveBom === 'boolean' ? variant.canHaveBom : null,
    bomLines: toArray(variant.bomLines)
      .filter((l) =>
        Number(l.quantity) > 0
        && (l.materialId || l.componentVariantId || l.componentSkuCode || l.componentRequestSkuKey))
      .map((l) => ({
        materialId: l.materialId || EMPTY_GUID,
        quantity: Number(l.quantity),
        componentVariantId: l.componentVariantId || null,
        componentSkuCode: trimOrNull(l.componentSkuCode),
        componentRequestSkuKey: trimOrNull(l.componentRequestSkuKey),
        isRequiredBaseComponent: Boolean(l.isRequiredBaseComponent),
      })),
  }
}

function buildVariantGeneratorBody(generator) {
  if (!generator || !toArray(generator.optionGroups).length) return null
  return {
    optionGroups: generator.optionGroups.map((group) => {
      const values = toArray(group.values).length
        ? group.values
        : String(group.valuesText || '').split(',')
      return {
        name: trimOrNull(group.name) || '',
        values: values.map((value) => String(value || '').trim()).filter(Boolean),
      }
    }),
    costPrice: Number(generator.costPrice || 0),
    retailPrice: Number(generator.retailPrice || 0),
    minStock: numberOrNull(generator.minStock),
    maxStock: numberOrNull(generator.maxStock),
    isSellable: generator.isSellable !== false,
    allowRewardPoints: generator.allowRewardPoints !== false,
  }
}

export function buildCreateProductBody(payload) {
  return {
    categoryId: Number(payload.categoryId),
    name: payload.name?.trim(),
    origin: trimOrNull(payload.origin),
    flavorProfile: trimOrNull(payload.flavorProfile),
    brewingGuide: trimOrNull(payload.brewingGuide),
    description: trimOrNull(payload.description),
    baseUnit: trimOrNull(payload.baseUnit) || 'unit',
    inventoryUnit: payload.inventoryUnit || null,
    weightValue: numberOrNull(payload.weightValue),
    weightUnit: trimOrNull(payload.weightUnit),
    productType: payload.productType || 'THANH_PHAM',
    isVariantParent: Boolean(payload.isVariantParent),
    images: toArray(payload.images).map(buildImageBody).filter((image) => image.imageUrl),
    units: toArray(payload.units).map(buildUnitBody).filter((unit) => unit.unitName),
    variants: toArray(payload.variants).map(buildVariantBody).filter((variant) => variant.variantName),
    variantGenerator: buildVariantGeneratorBody(payload.variantGenerator),
    attributes: toArray(payload.attributes)
      .map((attribute) => ({
        attributeNameId: attribute.attributeNameId || null,
        attributeName: trimOrNull(attribute.attributeName) || '',
        value: trimOrNull(attribute.value) || '',
      }))
      .filter((attribute) => attribute.attributeName && attribute.value),
  }
}

export function buildUpdateProductBody(payload) {
  const body = buildCreateProductBody(payload)
  if (payload.isActive === true || payload.isActive === false) {
    body.isActive = payload.isActive
  }
  return body
}

export async function createProduct(payload) {
  const data = await apiRequestAuth('/api/v1/products', {
    method: 'POST',
    body: JSON.stringify(buildCreateProductBody(payload)),
  })
  return mapProduct(data)
}

function mapProductApproval(item) {
  if (!item || typeof item !== 'object') return null
  const rawSkuIds = item.createdSkuIds ?? item.CreatedSkuIds ?? []
  return {
    id: item.id ?? item.Id,
    approvalCode: item.approvalCode ?? item.ApprovalCode ?? '',
    status: item.status ?? item.Status ?? '',
    productSnapshot: item.productSnapshot ?? item.ProductSnapshot ?? null,
    finalProductSnapshot: item.finalProductSnapshot ?? item.FinalProductSnapshot ?? null,
    productName: item.productName ?? item.ProductName ?? '',
    productType: item.productType ?? item.ProductType ?? '',
    categoryId: item.categoryId ?? item.CategoryId ?? null,
    initialPrice: numberOrNull(item.initialPrice ?? item.InitialPrice),
    requestedByName: item.requestedByName ?? item.RequestedByName ?? '',
    requestedByRoleName: item.requestedByRoleName ?? item.RequestedByRoleName ?? '',
    requestedAt: item.requestedAt ?? item.RequestedAt ?? null,
    authorisedByName: item.authorisedByName ?? item.AuthorisedByName ?? '',
    authorisedByRoleName: item.authorisedByRoleName ?? item.AuthorisedByRoleName ?? '',
    authorisedAt: item.authorisedAt ?? item.AuthorisedAt ?? null,
    confirmedByName: item.confirmedByName ?? item.ConfirmedByName ?? '',
    confirmedByRoleName: item.confirmedByRoleName ?? item.ConfirmedByRoleName ?? '',
    confirmedAt: item.confirmedAt ?? item.ConfirmedAt ?? null,
    cancelledByName: item.cancelledByName ?? item.CancelledByName ?? '',
    cancelledByRoleName: item.cancelledByRoleName ?? item.CancelledByRoleName ?? '',
    cancelledAt: item.cancelledAt ?? item.CancelledAt ?? null,
    cancelReason: item.cancelReason ?? item.CancelReason ?? '',
    creationMethod: item.creationMethod ?? item.CreationMethod ?? '',
    manualModeReason: item.manualModeReason ?? item.ManualModeReason ?? '',
    usedAt: item.usedAt ?? item.UsedAt ?? null,
    createdProductId: item.createdProductId ?? item.CreatedProductId ?? null,
    createdSkuIds: Array.isArray(rawSkuIds) ? rawSkuIds : [],
    adminNotes: item.adminNotes ?? item.AdminNotes ?? '',
    warehouseNotes: item.warehouseNotes ?? item.WarehouseNotes ?? '',
    createdAt: item.createdAt ?? item.CreatedAt ?? null,
    updatedAt: item.updatedAt ?? item.UpdatedAt ?? null,
  }
}

function mapProductCreationRequestItem(item) {
  if (!item || typeof item !== 'object') return null
  return {
    id: item.id ?? item.Id,
    clientKey: item.clientKey ?? item.ClientKey ?? '',
    sortOrder: Number(item.sortOrder ?? item.SortOrder ?? 0),
    productSnapshot: item.productSnapshot ?? item.ProductSnapshot ?? null,
    productName: item.productName ?? item.ProductName ?? '',
    productType: item.productType ?? item.ProductType ?? '',
    categoryId: item.categoryId ?? item.CategoryId ?? null,
    baseUnit: item.baseUnit ?? item.BaseUnit ?? '',
    inventoryUnit: item.inventoryUnit ?? item.InventoryUnit ?? '',
    variantCount: Number(item.variantCount ?? item.VariantCount ?? 0),
    bomLineCount: Number(item.bomLineCount ?? item.BomLineCount ?? 0),
    validationStatus: item.validationStatus ?? item.ValidationStatus ?? '',
    validationMessage: item.validationMessage ?? item.ValidationMessage ?? '',
  }
}

function mapProductCreationRevision(item) {
  if (!item || typeof item !== 'object') return null
  const rawItems = item.submittedItems ?? item.SubmittedItems ?? []
  return {
    id: item.id ?? item.Id,
    revisionNumber: Number(item.revisionNumber ?? item.RevisionNumber ?? 0),
    submittedItems: Array.isArray(rawItems) ? rawItems.map(mapProductCreationRequestItem).filter(Boolean) : [],
    submittedByName: item.submittedByName ?? item.SubmittedByName ?? '',
    submittedByRoleName: item.submittedByRoleName ?? item.SubmittedByRoleName ?? '',
    submittedAt: item.submittedAt ?? item.SubmittedAt ?? null,
    decision: item.decision ?? item.Decision ?? '',
    decisionReason: item.decisionReason ?? item.DecisionReason ?? '',
    decidedByName: item.decidedByName ?? item.DecidedByName ?? '',
    decidedByRoleName: item.decidedByRoleName ?? item.DecidedByRoleName ?? '',
    decidedAt: item.decidedAt ?? item.DecidedAt ?? null,
  }
}

function mapProductCreationRequest(item) {
  if (!item || typeof item !== 'object') return null
  const rawItems = item.items ?? item.Items ?? []
  const rawRevisions = item.revisions ?? item.Revisions ?? []
  const rawCreatedIds = item.createdProductIds ?? item.CreatedProductIds ?? []
  return {
    id: item.id ?? item.Id,
    requestCode: item.requestCode ?? item.RequestCode ?? '',
    title: item.title ?? item.Title ?? '',
    status: item.status ?? item.Status ?? '',
    revisionNumber: Number(item.revisionNumber ?? item.RevisionNumber ?? 0),
    createdBy: item.createdBy ?? item.CreatedBy ?? null,
    createdByName: item.createdByName ?? item.CreatedByName ?? '',
    createdByRoleName: item.createdByRoleName ?? item.CreatedByRoleName ?? '',
    createdAt: item.createdAt ?? item.CreatedAt ?? null,
    updatedAt: item.updatedAt ?? item.UpdatedAt ?? null,
    submittedAt: item.submittedAt ?? item.SubmittedAt ?? null,
    reviewedByName: item.reviewedByName ?? item.ReviewedByName ?? '',
    reviewedByRoleName: item.reviewedByRoleName ?? item.ReviewedByRoleName ?? '',
    reviewedAt: item.reviewedAt ?? item.ReviewedAt ?? null,
    rejectReason: item.rejectReason ?? item.RejectReason ?? '',
    cancelReason: item.cancelReason ?? item.CancelReason ?? '',
    warehouseNote: item.warehouseNote ?? item.WarehouseNote ?? '',
    adminNote: item.adminNote ?? item.AdminNote ?? '',
    completedAt: item.completedAt ?? item.CompletedAt ?? null,
    createdProductIds: Array.isArray(rawCreatedIds) ? rawCreatedIds : [],
    items: Array.isArray(rawItems) ? rawItems.map(mapProductCreationRequestItem).filter(Boolean) : [],
    revisions: Array.isArray(rawRevisions) ? rawRevisions.map(mapProductCreationRevision).filter(Boolean) : [],
  }
}

function mapProductDeletionRequestItem(item) {
  if (!item || typeof item !== 'object') return null
  return {
    id: item.id ?? item.Id,
    productId: item.productId ?? item.ProductId,
    productName: item.productName ?? item.ProductName ?? '',
    productType: item.productType ?? item.ProductType ?? '',
    categoryName: item.categoryName ?? item.CategoryName ?? '',
    variantCount: Number(item.variantCount ?? item.VariantCount ?? 0),
    reason: item.reason ?? item.Reason ?? '',
    validationStatus: item.validationStatus ?? item.ValidationStatus ?? '',
    validationMessage: item.validationMessage ?? item.ValidationMessage ?? '',
  }
}

function mapProductDeletionRevision(item) {
  if (!item || typeof item !== 'object') return null
  const rawItems = item.submittedItems ?? item.SubmittedItems ?? []
  return {
    id: item.id ?? item.Id,
    revisionNumber: Number(item.revisionNumber ?? item.RevisionNumber ?? 0),
    submittedItems: Array.isArray(rawItems) ? rawItems.map(mapProductDeletionRequestItem).filter(Boolean) : [],
    submittedByName: item.submittedByName ?? item.SubmittedByName ?? '',
    submittedByRoleName: item.submittedByRoleName ?? item.SubmittedByRoleName ?? '',
    submittedAt: item.submittedAt ?? item.SubmittedAt ?? null,
    decision: item.decision ?? item.Decision ?? '',
    decisionReason: item.decisionReason ?? item.DecisionReason ?? '',
    decidedByName: item.decidedByName ?? item.DecidedByName ?? '',
    decidedByRoleName: item.decidedByRoleName ?? item.DecidedByRoleName ?? '',
    decidedAt: item.decidedAt ?? item.DecidedAt ?? null,
  }
}

function mapProductDeletionRequest(item) {
  if (!item || typeof item !== 'object') return null
  const rawItems = item.items ?? item.Items ?? []
  const rawRevisions = item.revisions ?? item.Revisions ?? []
  const rawDeletedIds = item.deletedProductIds ?? item.DeletedProductIds ?? []
  return {
    id: item.id ?? item.Id,
    requestCode: item.requestCode ?? item.RequestCode ?? '',
    title: item.title ?? item.Title ?? '',
    status: item.status ?? item.Status ?? '',
    revisionNumber: Number(item.revisionNumber ?? item.RevisionNumber ?? 0),
    createdBy: item.createdBy ?? item.CreatedBy ?? null,
    createdByName: item.createdByName ?? item.CreatedByName ?? '',
    createdByRoleName: item.createdByRoleName ?? item.CreatedByRoleName ?? '',
    createdAt: item.createdAt ?? item.CreatedAt ?? null,
    updatedAt: item.updatedAt ?? item.UpdatedAt ?? null,
    submittedAt: item.submittedAt ?? item.SubmittedAt ?? null,
    reviewedByName: item.reviewedByName ?? item.ReviewedByName ?? '',
    reviewedByRoleName: item.reviewedByRoleName ?? item.ReviewedByRoleName ?? '',
    reviewedAt: item.reviewedAt ?? item.ReviewedAt ?? null,
    rejectReason: item.rejectReason ?? item.RejectReason ?? '',
    cancelReason: item.cancelReason ?? item.CancelReason ?? '',
    reason: item.reason ?? item.Reason ?? '',
    adminNote: item.adminNote ?? item.AdminNote ?? '',
    completedAt: item.completedAt ?? item.CompletedAt ?? null,
    deletedProductIds: Array.isArray(rawDeletedIds) ? rawDeletedIds : [],
    items: Array.isArray(rawItems) ? rawItems.map(mapProductDeletionRequestItem).filter(Boolean) : [],
    revisions: Array.isArray(rawRevisions) ? rawRevisions.map(mapProductDeletionRevision).filter(Boolean) : [],
  }
}

function buildProductCreationItems(items = []) {
  return items.map((item, index) => ({
    clientKey: item.clientKey || `item-${index + 1}`,
    product: buildCreateProductBody(item.product ?? item.productSnapshot ?? item),
  }))
}

export async function fetchProductCreationRequests(params = {}) {
  const search = new URLSearchParams()
  if (params.status) search.set('status', params.status)
  if (params.search) search.set('search', params.search)
  if (params.mineOnly) search.set('mineOnly', 'true')
  search.set('page', String(params.page ?? 1))
  search.set('pageSize', String(Math.min(100, Math.max(1, params.pageSize ?? 20))))
  const data = await apiRequestAuth(`/api/v1/product-creation-requests?${search.toString()}`, { method: 'GET' })
  const paged = toPagedResult(data)
  return {
    ...paged,
    items: paged.items.map(mapProductCreationRequest).filter(Boolean),
  }
}

export async function createProductCreationRequest(payload) {
  const data = await apiRequestAuth('/api/v1/product-creation-requests', {
    method: 'POST',
    body: JSON.stringify({
      title: trimOrNull(payload.title),
      warehouseNote: trimOrNull(payload.warehouseNote),
      items: buildProductCreationItems(payload.items),
    }),
  })
  return mapProductCreationRequest(data)
}

export async function updateProductCreationRequest(id, payload) {
  const data = await apiRequestAuth(`/api/v1/product-creation-requests/${id}`, {
    method: 'PUT',
    body: JSON.stringify({
      title: trimOrNull(payload.title),
      warehouseNote: trimOrNull(payload.warehouseNote),
      items: buildProductCreationItems(payload.items),
    }),
  })
  return mapProductCreationRequest(data)
}

export async function submitProductCreationRequest(id, warehouseNote = '') {
  const data = await apiRequestAuth(`/api/v1/product-creation-requests/${id}/submit`, {
    method: 'POST',
    body: JSON.stringify({ warehouseNote: trimOrNull(warehouseNote) }),
  })
  return mapProductCreationRequest(data)
}

export async function approveProductCreationRequest(id, adminNote = '') {
  const data = await apiRequestAuth(`/api/v1/product-creation-requests/${id}/approve`, {
    method: 'POST',
    body: JSON.stringify({ adminNote: trimOrNull(adminNote) }),
  })
  return mapProductCreationRequest(data)
}

export async function rejectProductCreationRequest(id, reason, adminNote = '') {
  const data = await apiRequestAuth(`/api/v1/product-creation-requests/${id}/reject`, {
    method: 'POST',
    body: JSON.stringify({ reason: String(reason || '').trim(), adminNote: trimOrNull(adminNote) }),
  })
  return mapProductCreationRequest(data)
}

export async function cancelProductCreationRequest(id, reason, adminNote = '') {
  const data = await apiRequestAuth(`/api/v1/product-creation-requests/${id}/cancel`, {
    method: 'POST',
    body: JSON.stringify({ reason: String(reason || '').trim(), adminNote: trimOrNull(adminNote) }),
  })
  return mapProductCreationRequest(data)
}

export async function fetchProductDeletionRequests(params = {}) {
  const search = new URLSearchParams()
  if (params.status) search.set('status', params.status)
  if (params.search) search.set('search', params.search)
  if (params.mineOnly) search.set('mineOnly', 'true')
  search.set('page', String(params.page ?? 1))
  search.set('pageSize', String(Math.min(100, Math.max(1, params.pageSize ?? 20))))
  const data = await apiRequestAuth(`/api/v1/product-deletion-requests?${search.toString()}`, { method: 'GET' })
  const paged = toPagedResult(data)
  return {
    ...paged,
    items: paged.items.map(mapProductDeletionRequest).filter(Boolean),
  }
}

export async function createProductDeletionRequest(payload) {
  const data = await apiRequestAuth('/api/v1/product-deletion-requests', {
    method: 'POST',
    body: JSON.stringify({
      title: trimOrNull(payload.title),
      reason: trimOrNull(payload.reason),
      items: toArray(payload.items).map((item) => ({
        productId: item.productId,
        reason: trimOrNull(item.reason),
      })),
    }),
  })
  return mapProductDeletionRequest(data)
}

export async function updateProductDeletionRequest(id, payload) {
  const data = await apiRequestAuth(`/api/v1/product-deletion-requests/${id}`, {
    method: 'PUT',
    body: JSON.stringify({
      title: trimOrNull(payload.title),
      reason: trimOrNull(payload.reason),
      items: toArray(payload.items).map((item) => ({
        productId: item.productId,
        reason: trimOrNull(item.reason),
      })),
    }),
  })
  return mapProductDeletionRequest(data)
}

export async function submitProductDeletionRequest(id, reason = '') {
  const data = await apiRequestAuth(`/api/v1/product-deletion-requests/${id}/submit`, {
    method: 'POST',
    body: JSON.stringify({ reason: trimOrNull(reason) }),
  })
  return mapProductDeletionRequest(data)
}

export async function approveProductDeletionRequest(id, adminNote = '') {
  const data = await apiRequestAuth(`/api/v1/product-deletion-requests/${id}/approve`, {
    method: 'POST',
    body: JSON.stringify({ adminNote: trimOrNull(adminNote) }),
  })
  return mapProductDeletionRequest(data)
}

export async function rejectProductDeletionRequest(id, reason, adminNote = '') {
  const data = await apiRequestAuth(`/api/v1/product-deletion-requests/${id}/reject`, {
    method: 'POST',
    body: JSON.stringify({ reason: String(reason || '').trim(), adminNote: trimOrNull(adminNote) }),
  })
  return mapProductDeletionRequest(data)
}

export async function cancelProductDeletionRequest(id, reason, adminNote = '') {
  const data = await apiRequestAuth(`/api/v1/product-deletion-requests/${id}/cancel`, {
    method: 'POST',
    body: JSON.stringify({ reason: String(reason || '').trim(), adminNote: trimOrNull(adminNote) }),
  })
  return mapProductDeletionRequest(data)
}

export async function fetchProductApprovals(params = {}) {
  const search = new URLSearchParams()
  if (params.status) search.set('status', params.status)
  if (params.search) search.set('search', params.search)
  search.set('page', String(params.page ?? 1))
  search.set('pageSize', String(Math.min(100, Math.max(1, params.pageSize ?? 20))))
  const data = await apiRequestAuth(`/api/v1/product-approval-requests?${search.toString()}`, { method: 'GET' })
  const paged = toPagedResult(data)
  return {
    ...paged,
    items: paged.items.map(mapProductApproval).filter(Boolean),
  }
}

export async function createProductApprovalRequest(payload) {
  const data = await apiRequestAuth('/api/v1/product-approval-requests', {
    method: 'POST',
    body: JSON.stringify({
      product: payload.product,
      adminNotes: trimOrNull(payload.adminNotes),
    }),
  })
  return mapProductApproval(data)
}

export async function authorizeProductApprovalRequest(id, adminNotes = '') {
  const data = await apiRequestAuth(`/api/v1/product-approval-requests/${id}/authorize`, {
    method: 'POST',
    body: JSON.stringify({ adminNotes: trimOrNull(adminNotes) }),
  })
  return mapProductApproval(data)
}

export async function cancelProductApprovalRequest(id, reason) {
  const data = await apiRequestAuth(`/api/v1/product-approval-requests/${id}/cancel`, {
    method: 'POST',
    body: JSON.stringify({ reason: String(reason || '').trim() }),
  })
  return mapProductApproval(data)
}

export async function validateProductApprovalCode(approvalCode) {
  const data = await apiRequestAuth('/api/v1/product-approval-requests/validate-code', {
    method: 'POST',
    body: JSON.stringify({ approvalCode: String(approvalCode || '').trim().toUpperCase() }),
  })
  return {
    isValid: Boolean(data?.isValid ?? data?.IsValid),
    message: data?.message ?? data?.Message ?? '',
    approval: mapProductApproval(data?.approval ?? data?.Approval),
  }
}

export async function createProductFromApproval(approvalCode) {
  const data = await apiRequestAuth('/api/v1/product-approval-requests/create-automatic', {
    method: 'POST',
    body: JSON.stringify({ approvalCode: String(approvalCode || '').trim().toUpperCase() }),
  })
  return {
    approval: mapProductApproval(data?.approval ?? data?.Approval),
    product: mapProduct(data?.product ?? data?.Product),
  }
}

export async function createProductManualFromApproval({ approvalCode, product, manualModeReason, warehouseNotes }) {
  const data = await apiRequestAuth('/api/v1/product-approval-requests/create-manual', {
    method: 'POST',
    body: JSON.stringify({
      approvalCode: String(approvalCode || '').trim().toUpperCase(),
      product: buildCreateProductBody(product),
      manualModeReason: String(manualModeReason || '').trim(),
      warehouseNotes: trimOrNull(warehouseNotes),
    }),
  })
  return {
    approval: mapProductApproval(data?.approval ?? data?.Approval),
    product: mapProduct(data?.product ?? data?.Product),
  }
}

export async function updateProduct(id, payload) {
  const data = await apiRequestAuth(`/api/v1/products/${id}`, {
    method: 'PUT',
    body: JSON.stringify(buildUpdateProductBody(payload)),
  })
  return mapProduct(data)
}

export async function deleteProduct(id) {
  return apiRequestAuth(`/api/v1/products/${id}`, { method: 'DELETE' })
}

export async function restoreProduct(id) {
  const data = await apiRequestAuth(`/api/v1/products/${id}/restore`, { method: 'POST' })
  return mapProduct(data)
}

export async function setProductStatus(product, isActive) {
  return updateProduct(product.id, {
    ...product,
    isActive,
  })
}
