namespace ProductService.Domain.Entities;

public class ProductVariant : BaseEntity
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid ProductId { get; set; }
    public string SkuCode { get; set; } = string.Empty;
    public string? Barcode { get; set; }
    public string VariantName { get; set; } = string.Empty;
    public string OptionValuesJson { get; set; } = "{}";
    public decimal CostPrice { get; set; }
    public decimal RetailPrice { get; set; }
    public int? MinStock { get; set; }
    public int? MaxStock { get; set; }
    public bool IsSellable { get; set; } = true;
    public bool AllowRewardPoints { get; set; } = true;
    public bool IsActive { get; set; } = true;
    public string? ImageUrl { get; set; }
    public int WeightInGrams { get; set; }
    public DateTime? SyncedToStoreAt { get; set; }
    public string? UnitName { get; set; }
    public decimal ConversionRate { get; set; } = 1;
    public Guid? BaseVariantId { get; set; }
    public bool IsBaseUnitVariant { get; set; }
    public bool IsAutoGeneratedSku { get; set; }

    public Product Product { get; set; } = null!;
    public ProductVariant? BaseVariant { get; set; }
    public ICollection<ProductVariant> DerivedVariants { get; set; } = new List<ProductVariant>();
    public ICollection<ProductUnit> Units { get; set; } = new List<ProductUnit>();
    public ICollection<PriceBookEntry> PriceBookEntries { get; set; } = new List<PriceBookEntry>();
    public ICollection<ProductVariantBomLine> BomLines { get; set; } = new List<ProductVariantBomLine>();
}
