// <auto-generated />
using InventoryService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace InventoryService.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260717101000_AddSkuStockLocationThresholds")]
    partial class AddSkuStockLocationThresholds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
