import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import PageShell from '../../../components/shared/PageShell.jsx'
import { showError, showSuccess, showToast } from '../../../app/toast.js'
import { useAuthSession } from '../../auth/hooks/useAuthSession.js'
import { isSystemAdmin, isWarehouseRole } from '../../auth/utils/permissions.js'
import VndCurrencyInput from '../components/VndCurrencyInput.jsx'
import { fetchAttributeNames } from '../services/attributeNamesApi.js'
import { fetchCategories } from '../services/categoriesApi.js'
import { searchMaterials } from '../services/bomApi.js'
import {
  approveProductCreationRequest,
  cancelProductCreationRequest,
  createProductCreationRequest,
  fetchProductCreationRequests,
  rejectProductCreationRequest,
  submitProductCreationRequest,
  updateProductCreationRequest,
} from '../services/productsApi.js'
import { formatDateTimeVN } from '../../../utils/vietnamDateTime.js'
import {
  PRODUCT_CREATION_TEMPLATE_FILENAME,
  buildGeneratedSkuCode,
  downloadOfficialProductCreationTemplate,
  exportProductCreationDraftToTemplate,
  formatProductCreationDraftExportFilename,
  hasMeaningfulProductCreationDraftData,
  parseOfficialProductCreationFile,
  validateAppendProductCreationImport,
} from '../utils/productCreationExcelWorkflow.js'
import {
  INVENTORY_UNIT_OPTIONS,
  PRODUCT_TYPE,
  PRODUCT_TYPE_OPTIONS,
  getDefaultSellableByType,
  getInventoryUnitShortLabel,
  getProductTypeLabel,
} from '../utils/productTypes.js'
import { formatWholeVnd, parseWholeVndInput } from '../utils/productDisplay.js'

const STATUS_LABELS = {
  Draft: 'Nháp',
  PendingApproval: 'Chờ Admin duyệt',
  Rejected: 'Bị từ chối',
  Completed: 'Đã tạo hàng hóa',
  Cancelled: 'Đã hủy',
}

const EMPTY_GUID = '00000000-0000-0000-0000-000000000000'
const BOM_INTEGER_MESSAGE = 'Định mức phải là số nguyên dương.'
const ATTRIBUTE_DUPLICATE_MESSAGE = 'Thuộc tính này đã được sử dụng cho sản phẩm.'
const ATTRIBUTE_VALUE_REQUIRED_MESSAGE = 'Vui lòng nhập giá trị thuộc tính.'
const ATTRIBUTE_NAME_SUGGESTIONS = [
  'Hương vị',
  'Màu sắc',
  'Xuất xứ',
  'Chất liệu bao bì',
  'Trọng lượng',
  'Cấp độ trà',
]

function createAttributeRow(overrides = {}) {
  return {
    clientKey: `attr-${Date.now()}-${Math.random().toString(16).slice(2)}`,
    attributeNameId: null,
    attributeName: '',
    value: '',
    ...overrides,
  }
}

function createDraftProduct() {
  const key = `item-${Date.now()}-${Math.random().toString(16).slice(2)}`
  const baseSkuKey = `${key}-base`
  return {
    clientKey: key,
    variantClientKey: baseSkuKey,
    name: '',
    productType: PRODUCT_TYPE.THANH_PHAM,
    categoryId: '',
    baseUnit: 'gói',
    inventoryUnit: 'Piece',
    description: '',
    skuCode: '',
    variantName: '',
    retailPrice: '',
    costPrice: '0',
    minStock: '0',
    maxStock: '',
    isSellable: true,
    bomLines: [],
    skuRows: [{
      requestSkuKey: baseSkuKey,
      unitName: 'gói',
      conversionRate: '1',
      skuCode: '',
      variantName: '',
      retailPrice: '',
      costPrice: '0',
      barcode: '',
      minStock: '0',
      maxStock: '',
      isSellable: true,
      isBaseUnitVariant: true,
      isAutoGeneratedSku: true,
      bomLines: [],
    }],
    attributes: [],
  }
}

function numberOrNull(value) {
  if (value === null || value === undefined || value === '') return null
  const number = Number(String(value).replace(',', '.'))
  return Number.isFinite(number) ? number : null
}

function positiveIntegerOrNull(value) {
  const text = normalizeText(value)
  if (!/^[1-9]\d*$/.test(text)) return null
  const number = Number(text)
  return Number.isSafeInteger(number) && number > 0 ? number : null
}

function preventNonIntegerKey(event) {
  if (['e', 'E', '+', '-', '.', ','].includes(event.key)) event.preventDefault()
}

function moneyOrNull(value) {
  return parseWholeVndInput(value)
}

function calculateDerivedRetailPrice(baseRetailPrice, conversionRate) {
  const basePrice = moneyOrNull(baseRetailPrice)
  const conversion = positiveIntegerOrNull(conversionRate)
  if (basePrice === null || conversion === null) return ''

  const amount = basePrice * conversion
  return Number.isSafeInteger(amount) && amount >= 0 ? String(amount) : ''
}

function normalizeText(value) {
  return String(value ?? '').trim()
}

function normalizeAttributeName(value) {
  const text = normalizeText(value).replace(/\s+/g, ' ').normalize('NFC')
  return text || ''
}

function getAttributeNameKey(value) {
  return normalizeAttributeName(value).toLocaleLowerCase('vi-VN')
}

function normalizeAttributeValue(value) {
  return normalizeText(value)
}

function normalizeAttributeRow(attribute) {
  return {
    ...attribute,
    clientKey: attribute.clientKey || `attr-${Date.now()}-${Math.random().toString(16).slice(2)}`,
    attributeNameId: attribute.attributeNameId || null,
    attributeName: normalizeAttributeName(attribute.attributeName),
    value: normalizeAttributeValue(attribute.value),
  }
}

function getSubmittableAttributes(attributes = []) {
  return attributes
    .map(normalizeAttributeRow)
    .filter((attribute) => attribute.attributeName || attribute.value)
}

function validateAttributeRows(attributes = [], prefix) {
  const errors = []
  const usedKeys = new Set()
  getSubmittableAttributes(attributes).forEach((attribute, index) => {
    const rowPrefix = `${prefix}, thuộc tính ${index + 1}`
    if (!attribute.attributeName && attribute.value) {
      errors.push(`${rowPrefix}: thiếu tên thuộc tính.`)
      return
    }
    if (attribute.attributeName && !attribute.value) {
      errors.push(`${rowPrefix}: ${ATTRIBUTE_VALUE_REQUIRED_MESSAGE}`)
    }
    if (attribute.attributeName.length > 100) {
      errors.push(`${rowPrefix}: tên thuộc tính tối đa 100 ký tự.`)
    }
    if (attribute.value.length > 500) {
      errors.push(`${rowPrefix}: giá trị thuộc tính tối đa 500 ký tự.`)
    }

    const key = getAttributeNameKey(attribute.attributeName)
    if (key && usedKeys.has(key)) {
      errors.push(`${rowPrefix}: ${ATTRIBUTE_DUPLICATE_MESSAGE}`)
    }
    if (key) usedKeys.add(key)
  })
  return errors
}

function createSkuRow(row, { isBase = false } = {}) {
  const key = `${row.clientKey}-sku-${Date.now()}-${Math.random().toString(16).slice(2)}`
  const baseSku = getSkuRows(row).find((sku) => sku.isBaseUnitVariant) ?? getSkuRows(row)[0]
  const basePrice = moneyOrNull(baseSku?.retailPrice) ?? moneyOrNull(row.retailPrice) ?? 0
  const conversionRate = isBase ? 1 : 10
  const unitName = isBase ? (row.baseUnit || 'gói') : ''
  return {
    requestSkuKey: key,
    unitName,
    conversionRate: String(conversionRate),
    skuCode: buildGeneratedSkuCode(row.name, unitName, conversionRate),
    variantName: unitName ? `${row.name || 'Sản phẩm'} - ${unitName}` : row.name,
    retailPrice: basePrice > 0 ? String(basePrice * conversionRate) : '',
    costPrice: String(moneyOrNull(row.costPrice) ?? 0),
    barcode: '',
    minStock: String(row.minStock ?? 0),
    maxStock: row.maxStock ?? '',
    isSellable: row.isSellable !== false,
    isBaseUnitVariant: isBase,
    isAutoGeneratedSku: true,
    baseRequestSkuKey: isBase ? null : baseSku?.requestSkuKey,
    baseSkuCode: isBase ? null : baseSku?.skuCode,
    bomLines: isBase || !baseSku
      ? []
      : [{
        materialId: EMPTY_GUID,
        materialName: row.name,
        materialUnitName: baseSku.unitName || row.baseUnit,
        quantity: conversionRate,
        componentRequestSkuKey: baseSku.requestSkuKey,
        componentSkuCode: baseSku.skuCode,
        componentVariantName: baseSku.variantName || baseSku.unitName,
        isRequiredBaseComponent: true,
      }],
  }
}

function getSkuRows(row) {
  if (Array.isArray(row.skuRows) && row.skuRows.length) return row.skuRows
  return [{
    requestSkuKey: row.variantClientKey || `${row.clientKey}-sku`,
    unitName: row.baseUnit || 'gói',
    conversionRate: '1',
    skuCode: row.skuCode || '',
    variantName: row.variantName || row.name || '',
    retailPrice: row.retailPrice ?? '',
    costPrice: row.costPrice ?? '0',
    barcode: '',
    minStock: row.minStock ?? '0',
    maxStock: row.maxStock ?? '',
    isSellable: row.isSellable !== false,
    isBaseUnitVariant: true,
    isAutoGeneratedSku: true,
    bomLines: row.bomLines ?? [],
  }]
}

function syncLegacySkuFields(row, skuRows) {
  const normalizedSkuRows = syncSkuRows(row, skuRows)
  const baseSku = normalizedSkuRows.find((sku) => sku.isBaseUnitVariant) ?? normalizedSkuRows[0] ?? {}
  return {
    ...row,
    skuRows: normalizedSkuRows,
    variantClientKey: baseSku.requestSkuKey || row.variantClientKey,
    baseUnit: baseSku.unitName || row.baseUnit,
    skuCode: baseSku.skuCode || '',
    variantName: baseSku.variantName || '',
    retailPrice: baseSku.retailPrice ?? '',
    costPrice: baseSku.costPrice ?? '0',
    minStock: baseSku.minStock ?? '0',
    maxStock: baseSku.maxStock ?? '',
    isSellable: baseSku.isSellable !== false,
    bomLines: baseSku.bomLines ?? [],
  }
}

function statusLabel(status) {
  return STATUS_LABELS[status] || status || '—'
}

function getPrimarySnapshotVariant(item) {
  const product = item?.productSnapshot ?? item?.ProductSnapshot ?? {}
  const variants = product.variants ?? product.Variants ?? []
  return Array.isArray(variants) ? variants[0] : null
}

function requestItemPriceSummary(item) {
  const variant = getPrimarySnapshotVariant(item)
  if (!variant) return ''
  const retailPrice = variant.retailPrice ?? variant.RetailPrice
  const costPrice = variant.costPrice ?? variant.CostPrice
  return `Giá bán: ${formatWholeVnd(retailPrice)} · Giá vốn: ${formatWholeVnd(costPrice)}`
}

function getMaterialUnit(material) {
  const inventoryUnit = getInventoryUnitShortLabel(material?.inventoryUnit)
  if (inventoryUnit) return inventoryUnit

  const baseUnit = material?.units?.find((unit) => unit.isBaseUnit) || material?.units?.[0]
  return material?.materialUnitName || material?.baseUnit || baseUnit?.unitName || ''
}

function getComponentSkuOptions(materials) {
  return materials.flatMap((material) => {
    const variants = material.variants?.length ? material.variants : material.skus ?? []
    return variants.map((variant) => ({
      productId: material.id,
      productName: material.name,
      productType: material.productType,
      materialUnitName: getMaterialUnit(material),
      variantId: variant.id,
      skuCode: variant.skuCode,
      variantName: variant.variantName || variant.packagingType || variant.unitName || material.name,
      unitName: variant.unitName || '',
    }))
  })
}

function createBomLineFromComponentSku(option, quantity = 1) {
  return {
    materialId: option.productId,
    materialName: option.productName,
    materialUnitName: option.materialUnitName,
    quantity,
    componentVariantId: option.variantId,
    componentSkuCode: option.skuCode,
    componentVariantName: option.variantName,
    isRequiredBaseComponent: false,
  }
}

function lineMatchesSku(line, sku) {
  if (!line || !sku) return false
  const lineRequestKey = normalizeText(line.componentRequestSkuKey)
  const lineSkuCode = normalizeText(line.componentSkuCode).toUpperCase()
  const lineVariantId = normalizeText(line.componentVariantId)
  const skuRequestKey = normalizeText(sku.requestSkuKey)
  const skuCode = normalizeText(sku.skuCode).toUpperCase()
  const skuVariantId = normalizeText(sku.variantId || sku.id)
  return Boolean(
    (lineRequestKey && skuRequestKey && lineRequestKey === skuRequestKey)
    || (lineSkuCode && skuCode && lineSkuCode === skuCode)
    || (lineVariantId && skuVariantId && lineVariantId === skuVariantId),
  )
}

function getBomComponentKey(line) {
  if (line?.componentVariantId) return `variant:${line.componentVariantId}`
  if (line?.componentSkuCode) return `sku:${normalizeText(line.componentSkuCode).toUpperCase()}`
  if (line?.componentRequestSkuKey) return `request:${line.componentRequestSkuKey}`
  return line?.materialId ? `material:${line.materialId}` : ''
}

function createRequiredBaseBomLine(row, sku, baseSku) {
  return {
    materialId: EMPTY_GUID,
    materialName: row.name,
    materialUnitName: baseSku.unitName || row.baseUnit,
    quantity: normalizeText(sku.conversionRate) || '',
    componentRequestSkuKey: baseSku.requestSkuKey,
    componentSkuCode: baseSku.skuCode,
    componentVariantName: baseSku.variantName || baseSku.unitName,
    isRequiredBaseComponent: true,
  }
}

function syncRequiredBaseBomLines(row, skuRows) {
  const normalizedRows = Array.isArray(skuRows) ? skuRows : []
  if (row.productType !== PRODUCT_TYPE.THANH_PHAM) {
    return normalizedRows.map((sku) => ({ ...sku, bomLines: [] }))
  }

  const baseIndex = normalizedRows.findIndex((sku) => sku.isBaseUnitVariant)
  const baseSku = normalizedRows[baseIndex >= 0 ? baseIndex : 0]
  if (!baseSku) return normalizedRows

  return normalizedRows.map((sku, index) => {
    const isBase = index === (baseIndex >= 0 ? baseIndex : 0)
    const manualLines = (sku.bomLines ?? []).filter((line) => {
      if (line.isRequiredBaseComponent) return false
      if (!isBase && lineMatchesSku(line, baseSku)) return false
      return true
    })

    if (isBase) {
      return {
        ...sku,
        isBaseUnitVariant: true,
        conversionRate: '1',
        baseRequestSkuKey: null,
        baseSkuCode: null,
        bomLines: manualLines,
      }
    }

    return {
      ...sku,
      isBaseUnitVariant: false,
      baseRequestSkuKey: baseSku.requestSkuKey,
      baseSkuCode: baseSku.skuCode,
      bomLines: [createRequiredBaseBomLine(row, sku, baseSku), ...manualLines],
    }
  })
}

function syncDerivedSkuRetailPrices(skuRows) {
  const normalizedRows = Array.isArray(skuRows) ? skuRows : []
  const baseIndex = normalizedRows.findIndex((sku) => sku.isBaseUnitVariant)
  const baseSku = normalizedRows[baseIndex >= 0 ? baseIndex : 0]
  if (!baseSku) return normalizedRows

  return normalizedRows.map((sku, index) => {
    const isBase = index === (baseIndex >= 0 ? baseIndex : 0)
    if (isBase) {
      return {
        ...sku,
        isBaseUnitVariant: true,
        conversionRate: '1',
      }
    }

    return {
      ...sku,
      isBaseUnitVariant: false,
      retailPrice: calculateDerivedRetailPrice(baseSku.retailPrice, sku.conversionRate),
    }
  })
}

function syncSkuRows(row, skuRows) {
  return syncRequiredBaseBomLines(row, syncDerivedSkuRetailPrices(skuRows))
}

function normalizeBomLine(line, materialsById) {
  const materialId = line.materialId ?? line.material_id ?? line.MaterialId
  const material = materialId ? materialsById.get(String(materialId)) : null
  const componentSkuCode = line.componentSkuCode ?? line.ComponentSkuCode ?? ''
  const componentVariantName = line.componentVariantName ?? line.ComponentVariantName ?? ''
  return {
    materialId,
    materialName: line.materialName ?? line.MaterialName ?? componentVariantName ?? material?.name ?? '',
    materialUnitName:
      line.materialUnitName ??
      line.MaterialUnitName ??
      line.baseUnit ??
      line.BaseUnit ??
      getMaterialUnit(material),
    quantity: numberOrNull(line.quantity ?? line.Quantity) ?? 1,
    componentVariantId: line.componentVariantId ?? line.ComponentVariantId ?? null,
    componentSkuCode,
    componentRequestSkuKey: line.componentRequestSkuKey ?? line.ComponentRequestSkuKey ?? null,
    componentVariantName,
    isRequiredBaseComponent: Boolean(line.isRequiredBaseComponent ?? line.IsRequiredBaseComponent ?? false),
  }
}

function toProductPayload(row) {
  const isFinishedProduct = row.productType === PRODUCT_TYPE.THANH_PHAM
  const skuRows = syncSkuRows(row, getSkuRows(row))
  const baseSku = skuRows.find((sku) => sku.isBaseUnitVariant) ?? skuRows[0]
  const baseUnit = baseSku?.unitName || row.baseUnit || 'unit'

  return {
    categoryId: Number(row.categoryId),
    name: row.name.trim(),
    origin: '',
    flavorProfile: '',
    brewingGuide: '',
    description: row.description?.trim() || '',
    baseUnit,
    inventoryUnit: row.inventoryUnit || 'Piece',
    weightValue: null,
    weightUnit: null,
    isVariantParent: true,
    productType: row.productType,
    images: [],
    units: skuRows.map((sku) => {
      const price = moneyOrNull(sku.retailPrice)
      return {
        unitName: sku.unitName || baseUnit,
        conversionRate: Number(sku.conversionRate || 1),
        price: price && price > 0 ? price : null,
        barcode: normalizeText(sku.barcode),
        isDirectSell: sku.isSellable !== false,
        isBaseUnit: Boolean(sku.isBaseUnitVariant),
      }
    }),
    variants: skuRows.map((sku) => {
      const retailPrice = moneyOrNull(sku.retailPrice) ?? 0
      const costPrice = moneyOrNull(sku.costPrice) ?? 0
      return {
        requestSkuKey: sku.requestSkuKey,
        skuCode: normalizeText(sku.skuCode).toUpperCase(),
        barcode: normalizeText(sku.barcode),
        variantName: normalizeText(sku.variantName) || `${row.name.trim()} - ${sku.unitName || baseUnit}`,
        optionValuesJson: '{}',
        costPrice,
        retailPrice,
        minStock: numberOrNull(sku.minStock),
        maxStock: numberOrNull(sku.maxStock),
        isSellable: sku.isSellable !== false,
        allowRewardPoints: true,
        isActive: true,
        imageUrl: '',
        unitName: sku.unitName || baseUnit,
        conversionRate: Number(sku.conversionRate || 1),
        baseRequestSkuKey: sku.isBaseUnitVariant ? null : (sku.baseRequestSkuKey || baseSku?.requestSkuKey || null),
        baseSkuCode: sku.isBaseUnitVariant ? null : (sku.baseSkuCode || baseSku?.skuCode || null),
        isBaseUnitVariant: Boolean(sku.isBaseUnitVariant),
        isAutoGeneratedSku: sku.isAutoGeneratedSku !== false,
        units: [{
          unitName: sku.unitName || baseUnit,
          conversionRate: 1,
          price: retailPrice > 0 ? retailPrice : null,
          barcode: normalizeText(sku.barcode),
          isDirectSell: sku.isSellable !== false,
          isBaseUnit: true,
        }],
        bomLines: isFinishedProduct
          ? (sku.bomLines ?? [])
            .filter((line) => positiveIntegerOrNull(line.quantity) && (line.materialId || line.componentVariantId || line.componentSkuCode || line.componentRequestSkuKey))
            .map((line) => ({
              materialId: line.materialId || EMPTY_GUID,
              quantity: positiveIntegerOrNull(line.quantity),
              componentVariantId: line.componentVariantId || null,
              componentSkuCode: normalizeText(line.componentSkuCode),
              componentRequestSkuKey: normalizeText(line.componentRequestSkuKey),
              isRequiredBaseComponent: Boolean(line.isRequiredBaseComponent),
            }))
          : [],
      }
    }),
    attributes: getSubmittableAttributes(row.attributes)
      .map((attribute) => ({
        attributeNameId: attribute.attributeNameId || null,
        attributeName: attribute.attributeName,
        value: attribute.value,
      })),
    variantGenerator: null,
  }
}

function fromProductSnapshot(item, materialsById) {
  const product = item.productSnapshot ?? {}
  const variants = Array.isArray(product.variants) ? product.variants : []
  const skuRows = variants.map((variant, index) => ({
    variantId: variant.id ?? variant.variantId ?? null,
    requestSkuKey: variant.requestSkuKey || variant.skuCode || `${item.clientKey || Date.now()}-sku-${index + 1}`,
    unitName: variant.unitName || variant.units?.[0]?.unitName || product.baseUnit || 'gói',
    conversionRate: String(variant.conversionRate ?? (index === 0 ? 1 : '')),
    skuCode: variant.skuCode || '',
    variantName: variant.variantName || '',
    retailPrice: String(variant.retailPrice ?? ''),
    costPrice: String(variant.costPrice ?? 0),
    barcode: variant.barcode || '',
    minStock: String(variant.minStock ?? 0),
    maxStock: variant.maxStock == null ? '' : String(variant.maxStock),
    isSellable: variant.isSellable !== false,
    isBaseUnitVariant: Boolean(variant.isBaseUnitVariant ?? index === 0),
    isAutoGeneratedSku: variant.isAutoGeneratedSku !== false,
    baseRequestSkuKey: variant.baseRequestSkuKey ?? null,
    baseSkuCode: variant.baseSkuCode ?? null,
    bomLines: Array.isArray(variant.bomLines)
      ? variant.bomLines.map((line) => normalizeBomLine(line, materialsById))
      : [],
  }))
  const baseSku = skuRows.find((sku) => sku.isBaseUnitVariant) ?? skuRows[0] ?? {}
  const fallbackDraft = { ...createDraftProduct(), name: product.name || '' }
  const fallbackSkuRows = getSkuRows(fallbackDraft)

  return syncLegacySkuFields({
    clientKey: item.clientKey || `item-${Date.now()}`,
    variantClientKey: baseSku.requestSkuKey || `${item.clientKey || Date.now()}-sku`,
    name: product.name || '',
    description: product.description || '',
    productType: product.productType || PRODUCT_TYPE.THANH_PHAM,
    categoryId: product.categoryId ? String(product.categoryId) : '',
    baseUnit: baseSku.unitName || product.baseUnit || 'gói',
    inventoryUnit: product.inventoryUnit || 'Piece',
    skuCode: baseSku.skuCode || '',
    variantName: baseSku.variantName || '',
    retailPrice: baseSku.retailPrice ?? '',
    costPrice: baseSku.costPrice ?? '0',
    minStock: baseSku.minStock ?? '0',
    maxStock: baseSku.maxStock ?? '',
    isSellable: baseSku.isSellable !== false,
    bomLines: baseSku.bomLines ?? [],
    skuRows: skuRows.length ? skuRows : fallbackSkuRows,
    attributes: Array.isArray(product.attributes)
      ? product.attributes.map((attribute) => normalizeAttributeRow({
        attributeNameId: attribute.attributeNameId ?? null,
        attributeName: attribute.attributeName ?? '',
        value: attribute.value ?? '',
      }))
      : [],
  }, skuRows.length ? skuRows : fallbackSkuRows)
}

function validateForm(title, rows) {
  const errors = []
  if (!title.trim()) errors.push('Tiêu đề yêu cầu là bắt buộc.')
  if (!rows.length) errors.push('Cần ít nhất một sản phẩm.')

  const skuCodes = new Set()
  const names = new Set()
  rows.forEach((row, index) => {
    const prefix = `Sản phẩm ${index + 1}`
    const isFinishedProduct = row.productType === PRODUCT_TYPE.THANH_PHAM
    const skuRows = syncSkuRows(row, getSkuRows(row))
    if (!row.name.trim()) errors.push(`${prefix}: thiếu tên sản phẩm.`)
    if (!row.categoryId) errors.push(`${prefix}: thiếu danh mục.`)
    if (row.name.trim()) {
      const nameKey = row.name.trim().toLowerCase()
      if (names.has(nameKey)) errors.push(`${prefix}: tên sản phẩm bị trùng trong yêu cầu.`)
      names.add(nameKey)
    }
    errors.push(...validateAttributeRows(row.attributes, prefix))

    if (!skuRows.length) errors.push(`${prefix}: cần ít nhất một SKU.`)
    const baseCount = skuRows.filter((sku) => sku.isBaseUnitVariant).length
    if (skuRows.length && baseCount !== 1) errors.push(`${prefix}: cần đúng một SKU đơn vị cơ bản.`)

    skuRows.forEach((sku, skuIndex) => {
      const skuPrefix = `${prefix}, SKU ${skuIndex + 1}`
      if (!normalizeText(sku.unitName)) errors.push(`${skuPrefix}: thiếu tên đơn vị.`)
      if (!normalizeText(sku.skuCode)) errors.push(`${skuPrefix}: thiếu mã SKU.`)
      const conversionRate = positiveIntegerOrNull(sku.conversionRate)
      if (!conversionRate) errors.push(`${skuPrefix}: quy đổi phải là số nguyên dương.`)
      if (sku.isBaseUnitVariant && conversionRate !== 1) errors.push(`${skuPrefix}: SKU đơn vị cơ bản phải có quy đổi bằng 1.`)
      if (normalizeText(sku.skuCode)) {
        const skuKey = normalizeText(sku.skuCode).toUpperCase()
        if (skuCodes.has(skuKey)) errors.push(`${skuPrefix}: SKU bị trùng trong yêu cầu.`)
        skuCodes.add(skuKey)
      }

      const retailPrice = moneyOrNull(sku.retailPrice)
      const costPrice = moneyOrNull(sku.costPrice)
      if (normalizeText(sku.retailPrice) && retailPrice === null) errors.push(`${skuPrefix}: giá bán không hợp lệ.`)
      if (normalizeText(sku.costPrice) && costPrice === null) errors.push(`${skuPrefix}: giá vốn không hợp lệ.`)
      if ((retailPrice ?? 0) <= 0 && sku.isSellable) errors.push(`${skuPrefix}: SKU bán trực tiếp cần giá bán > 0.`)
      if (!isFinishedProduct && (sku.bomLines ?? []).length > 0) errors.push(`${skuPrefix}: BOM chỉ áp dụng cho Sản phẩm kệ.`)

      const components = new Set()
      ;(sku.bomLines ?? []).forEach((line, lineIndex) => {
        const linePrefix = `${skuPrefix}, BOM ${lineIndex + 1}`
        const componentKey = line.componentVariantId || line.componentSkuCode || line.componentRequestSkuKey || line.materialId
        if (!componentKey) errors.push(`${linePrefix}: thiếu component SKU.`)
        if (componentKey && components.has(String(componentKey))) errors.push(`${linePrefix}: component bị trùng.`)
        if (componentKey) components.add(String(componentKey))
        if (!positiveIntegerOrNull(line.quantity)) errors.push(`${linePrefix}: ${BOM_INTEGER_MESSAGE}`)
      })
    })
  })

  return errors
}

function buildAttributeNameOptions(attributeNames = [], rows = []) {
  const byKey = new Map()
  const addOption = (name, source, id = null) => {
    const label = normalizeAttributeName(name)
    const key = getAttributeNameKey(label)
    if (!key || byKey.has(key)) return
    byKey.set(key, { key, id, name: label, source })
  }

  toReferenceArray(attributeNames)
    .filter((item) => item && (item.isDeleted ?? item.IsDeleted) !== true && (item.isActive ?? item.IsActive) !== false)
    .forEach((item) => addOption(
      item.name ?? item.Name ?? item.attributeName ?? item.AttributeName ?? item.displayName ?? item.DisplayName,
      'existing',
      item.id ?? item.Id,
    ))
  ATTRIBUTE_NAME_SUGGESTIONS.forEach((name) => addOption(name, 'suggestion'))
  rows.forEach((row) => {
    ;(row.attributes ?? []).forEach((attribute) => addOption(attribute.attributeName, 'request', attribute.attributeNameId ?? null))
  })

  return Array.from(byKey.values()).sort((left, right) => left.name.localeCompare(right.name, 'vi'))
}

function buildAttributeNameLookup(options = []) {
  return new Map(options.map((option) => [option.key, option]))
}

function toReferenceArray(value) {
  if (Array.isArray(value)) return value
  if (!value || typeof value !== 'object') return []

  const candidateKeys = ['items', 'Items', 'records', 'Records', 'list', 'List', 'result', 'Result', 'data', 'Data']
  for (const key of candidateKeys) {
    const candidate = value[key]
    if (Array.isArray(candidate)) return candidate
    const nested = toReferenceArray(candidate)
    if (nested.length) return nested
  }

  return []
}

const EXCEL_REFERENCE_SOURCES = {
  categories: {
    label: 'Categories',
    userMessage: 'Không tải được danh mục sản phẩm.',
  },
  componentSkus: {
    label: 'Component SKUs',
    userMessage: 'Không tải được danh sách Component SKU.',
  },
  attributeNames: {
    label: 'Attribute Names',
    userMessage: 'Không tải được danh sách tên thuộc tính.',
  },
}

function getReferenceFailureMessage(error) {
  return normalizeText(error?.message ?? error?.Message ?? error?.statusText ?? error) || 'Không rõ nguyên nhân'
}

function buildReferenceLoadEntry(sourceKey, result, fallbackItems = []) {
  const source = EXCEL_REFERENCE_SOURCES[sourceKey]
  if (result.status === 'fulfilled') {
    const items = toReferenceArray(result.value)
    return {
      items,
      failure: null,
      status: {
        source: source.label,
        status: 'OK',
        message: `OK: ${items.length} items`,
      },
    }
  }

  const items = toReferenceArray(fallbackItems)
  const message = getReferenceFailureMessage(result.reason)
  return {
    items,
    failure: {
      source: sourceKey,
      message: source.userMessage,
      detail: message,
    },
    status: {
      source: source.label,
      status: 'Failed',
      message: `Failed: ${message}`,
    },
  }
}

function showReferenceWarningToast(failures = []) {
  if (!failures.length) return
  const details = failures.map((failure) => failure.message).join(' ')
  showToast(
    `File mẫu đã được tải nhưng thiếu một số dữ liệu tham chiếu. Vui lòng kiểm tra sheet tham chiếu hoặc nhập tay nếu cần. ${details}`,
    'warning',
  )
}

function SkuComponentCombobox({ options, onSelect }) {
  const [query, setQuery] = useState('')
  const [isOpen, setIsOpen] = useState(false)
  const [highlightedIndex, setHighlightedIndex] = useState(0)
  const filteredOptions = useMemo(() => {
    const keyword = normalizeText(query).toLowerCase()
    const source = keyword
      ? options.filter((option) => [
        option.skuCode,
        option.productName,
        option.variantName,
        option.unitName,
        option.productTypeLabel,
        option.sourceLabel,
      ].some((value) => normalizeText(value).toLowerCase().includes(keyword)))
      : options
    return source.slice(0, 20)
  }, [options, query])

  function selectOption(option) {
    if (!option) return
    onSelect(option)
    setQuery('')
    setIsOpen(false)
    setHighlightedIndex(0)
  }

  return (
    <div className="relative w-full max-w-md">
      <input
        className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm focus:border-[#356647] focus:outline-none focus:ring-2 focus:ring-[#356647]/15"
        placeholder="Tìm component SKU..."
        value={query}
        onFocus={() => setIsOpen(true)}
        onBlur={() => window.setTimeout(() => setIsOpen(false), 120)}
        onChange={(event) => {
          setQuery(event.target.value)
          setIsOpen(true)
          setHighlightedIndex(0)
        }}
        onKeyDown={(event) => {
          if (event.key === 'Escape') {
            setIsOpen(false)
            return
          }
          if (event.key === 'ArrowDown') {
            event.preventDefault()
            setIsOpen(true)
            setHighlightedIndex((current) => Math.min(current + 1, Math.max(filteredOptions.length - 1, 0)))
            return
          }
          if (event.key === 'ArrowUp') {
            event.preventDefault()
            setHighlightedIndex((current) => Math.max(current - 1, 0))
            return
          }
          if (event.key === 'Enter') {
            event.preventDefault()
            selectOption(filteredOptions[highlightedIndex])
          }
        }}
      />
      {isOpen ? (
        <div className="absolute left-0 right-0 top-full z-20 mt-1 max-h-72 overflow-y-auto rounded-xl border border-slate-200 bg-white shadow-lg">
          {filteredOptions.length === 0 ? (
            <p className="px-4 py-3 text-sm text-slate-400">Không tìm thấy SKU phù hợp</p>
          ) : null}
          {filteredOptions.map((option, index) => (
            <button
              key={option.key}
              type="button"
              className={`block w-full px-4 py-2.5 text-left text-sm ${index === highlightedIndex ? 'bg-[#f0eee6]' : 'hover:bg-slate-50'}`}
              onMouseDown={(event) => event.preventDefault()}
              onClick={() => selectOption(option)}
            >
              <span className="block font-mono text-xs font-semibold text-[#356647]">{option.skuCode}</span>
              <span className="block font-medium text-slate-800">
                {option.productName}{option.unitName ? ` · ${option.unitName}` : ''}
              </span>
              <span className="text-xs text-slate-500">
                {[option.variantName, option.productTypeLabel, option.sourceLabel].filter(Boolean).join(' · ')}
              </span>
            </button>
          ))}
        </div>
      ) : null}
    </div>
  )
}

function AttributeNameCombobox({
  value,
  options,
  usedKeys,
  onSelect,
  autoFocus = false,
  onFocused,
}) {
  const rootRef = useRef(null)
  const inputRef = useRef(null)
  const [isOpen, setIsOpen] = useState(false)
  const [query, setQuery] = useState('')
  const [highlightedIndex, setHighlightedIndex] = useState(0)
  const selectedName = normalizeAttributeName(value)
  const queryName = normalizeAttributeName(query)
  const queryKey = getAttributeNameKey(queryName)

  const filteredOptions = useMemo(() => {
    const searchKey = queryKey
    return options
      .filter((option) => !usedKeys.has(option.key))
      .filter((option) => !searchKey || option.key.includes(searchKey) || option.name.toLocaleLowerCase('vi-VN').includes(searchKey))
      .slice(0, 8)
  }, [options, queryKey, usedKeys])

  const hasExactMatch = options.some((option) => option.key === queryKey)
  const isDuplicateName = Boolean(queryKey && usedKeys.has(queryKey))
  const canCreate = Boolean(queryName && !hasExactMatch && !isDuplicateName)
  const resultItems = [
    ...filteredOptions.map((option) => ({ type: 'option', key: option.key, label: option.name, option })),
    ...(canCreate ? [{ type: 'create', key: `create:${queryKey}`, label: `+ Tạo thuộc tính “${queryName}”`, option: { id: null, name: queryName, key: queryKey } }] : []),
  ]

  useEffect(() => {
    if (!autoFocus) return
    const timer = window.setTimeout(() => {
      inputRef.current?.focus()
      setIsOpen(true)
      setQuery('')
      onFocused?.()
    }, 0)
    return () => window.clearTimeout(timer)
  }, [autoFocus, onFocused])

  useEffect(() => {
    const handlePointerDown = (event) => {
      if (!rootRef.current?.contains(event.target)) {
        setIsOpen(false)
        setQuery('')
      }
    }
    document.addEventListener('mousedown', handlePointerDown)
    return () => document.removeEventListener('mousedown', handlePointerDown)
  }, [])

  function commitOption(item) {
    if (!item || item.disabled) return
    onSelect({
      attributeNameId: item.option.id ?? null,
      attributeName: item.option.name,
    })
    setIsOpen(false)
    setQuery('')
  }

  return (
    <div ref={rootRef} className="relative">
      <div className="flex items-center rounded-lg border border-slate-200 bg-white focus-within:border-[#538463]">
        <input
          ref={inputRef}
          type="text"
          role="combobox"
          aria-expanded={isOpen}
          autoComplete="off"
          className="min-w-0 flex-1 rounded-lg px-3 py-2 text-sm outline-none"
          placeholder="Tìm hoặc nhập tên thuộc tính..."
          value={isOpen ? query : selectedName}
          onFocus={() => {
            setIsOpen(true)
            setQuery('')
            setHighlightedIndex(0)
          }}
          onChange={(event) => {
            setQuery(event.target.value)
            setHighlightedIndex(0)
            if (!isOpen) setIsOpen(true)
          }}
          onKeyDown={(event) => {
            if (event.key === 'ArrowDown') {
              event.preventDefault()
              setIsOpen(true)
              setHighlightedIndex((current) => Math.min(current + 1, Math.max(resultItems.length - 1, 0)))
            }
            if (event.key === 'ArrowUp') {
              event.preventDefault()
              setHighlightedIndex((current) => Math.max(current - 1, 0))
            }
            if (event.key === 'Enter' && isOpen) {
              event.preventDefault()
              commitOption(resultItems[highlightedIndex])
            }
            if (event.key === 'Escape') {
              setIsOpen(false)
              setQuery('')
            }
          }}
        />
        {selectedName ? (
          <button
            type="button"
            className="mr-2 rounded-md px-2 py-1 text-xs font-semibold text-slate-400 hover:bg-slate-100"
            title="Xóa thuộc tính"
            onClick={() => onSelect({ attributeNameId: null, attributeName: '' })}
          >
            x
          </button>
        ) : null}
      </div>

      {isOpen ? (
        <div className="absolute left-0 right-0 top-full z-30 mt-1 max-h-64 overflow-y-auto rounded-xl border border-slate-200 bg-white shadow-lg">
          {resultItems.length === 0 && !isDuplicateName ? (
            <p className="px-4 py-3 text-sm text-slate-400">Không tìm thấy thuộc tính phù hợp.</p>
          ) : null}
          {isDuplicateName ? (
            <p className="px-4 py-3 text-sm font-semibold text-amber-700">Đã được sử dụng</p>
          ) : null}
          {resultItems.map((item, index) => (
            <button
              key={item.key}
              type="button"
              className={`block w-full px-4 py-2.5 text-left text-sm ${index === highlightedIndex ? 'bg-[#f0eee6]' : 'hover:bg-slate-50'} ${item.type === 'create' ? 'font-semibold text-[#356647]' : 'text-slate-800'}`}
              onMouseDown={(event) => event.preventDefault()}
              onClick={() => commitOption(item)}
            >
              {item.label}
              {item.type === 'option' && item.option.source === 'existing' ? (
                <span className="ml-2 text-[11px] font-semibold text-slate-400">Đã có</span>
              ) : null}
            </button>
          ))}
        </div>
      ) : null}
    </div>
  )
}

function ProductRow({ row, categories, materials, attributeNameOptions, onChange, onRemove, canRemove }) {
  const isFinishedProduct = row.productType === PRODUCT_TYPE.THANH_PHAM
  const skuRows = syncSkuRows(row, getSkuRows(row))
  const componentSkuOptions = getComponentSkuOptions(materials)
  const attributes = row.attributes ?? []
  const [pendingAttributeFocusKey, setPendingAttributeFocusKey] = useState(null)

  function applySkuRows(nextRow, nextSkuRows) {
    onChange(syncLegacySkuFields(nextRow, nextSkuRows))
  }

  function updateProduct(changes) {
    const nextRow = { ...row, ...changes }
    const nextSkuRows = skuRows.map((sku) => {
      const unitName = changes.baseUnit && sku.isBaseUnitVariant ? changes.baseUnit : sku.unitName
      const conversionRate = sku.isBaseUnitVariant ? 1 : sku.conversionRate
      const autoSku = sku.isAutoGeneratedSku !== false
      return {
        ...sku,
        unitName,
        conversionRate: String(conversionRate),
        skuCode: autoSku ? buildGeneratedSkuCode(nextRow.name, unitName, conversionRate) : sku.skuCode,
        variantName: `${nextRow.name || 'Sản phẩm'} - ${unitName || 'đơn vị'}`,
        bomLines: nextRow.productType === PRODUCT_TYPE.THANH_PHAM ? sku.bomLines : [],
      }
    })
    applySkuRows(nextRow, nextSkuRows)
  }

  function updateSku(index, changes) {
    const nextSkuRows = skuRows.map((sku, currentIndex) => {
      if (currentIndex !== index) return sku
      const unitName = changes.unitName ?? sku.unitName
      const conversionRate = changes.isBaseUnitVariant || sku.isBaseUnitVariant
        ? 1
        : (changes.conversionRate ?? sku.conversionRate)
      const autoSku = changes.isAutoGeneratedSku ?? sku.isAutoGeneratedSku ?? true
      return {
        ...sku,
        ...changes,
        unitName,
        conversionRate: String(conversionRate),
        skuCode: autoSku ? buildGeneratedSkuCode(row.name, unitName, conversionRate) : (changes.skuCode ?? sku.skuCode),
        variantName: changes.variantName ?? `${row.name || 'Sản phẩm'} - ${unitName || 'đơn vị'}`,
        isAutoGeneratedSku: autoSku,
      }
    })
    applySkuRows(row, nextSkuRows)
  }

  function addSku() {
    applySkuRows(row, [...skuRows, createSkuRow(row, { isBase: false })])
  }

  function removeSku(index) {
    const target = skuRows[index]
    if (target?.isBaseUnitVariant) return
    applySkuRows(row, skuRows.filter((_, currentIndex) => currentIndex !== index))
  }

  function markBaseSku(index) {
    const baseSku = skuRows[index]
    const nextSkuRows = skuRows.map((sku, currentIndex) => ({
      ...sku,
      isBaseUnitVariant: currentIndex === index,
      conversionRate: currentIndex === index ? '1' : sku.conversionRate,
      baseRequestSkuKey: currentIndex === index ? null : baseSku.requestSkuKey,
      baseSkuCode: currentIndex === index ? null : baseSku.skuCode,
    }))
    applySkuRows({ ...row, baseUnit: baseSku.unitName || row.baseUnit }, nextSkuRows)
  }

  function getAvailableComponentOptions(skuIndex) {
    const sku = skuRows[skuIndex]
    const selectedKeys = new Set((sku?.bomLines ?? []).map(getBomComponentKey).filter(Boolean))
    const localOptions = skuRows
      .filter((option) => option.requestSkuKey !== sku?.requestSkuKey && option.skuCode)
      .map((option) => ({
        key: `local:${option.requestSkuKey}`,
        sourceType: 'local',
        requestSkuKey: option.requestSkuKey,
        skuCode: option.skuCode,
        productName: row.name,
        variantName: option.variantName || option.unitName,
        unitName: option.unitName,
        productType: row.productType,
        productTypeLabel: getProductTypeLabel(row.productType),
        sourceLabel: 'SKU cùng request',
      }))
      .filter((option) =>
        !selectedKeys.has(`request:${option.requestSkuKey}`)
        && !selectedKeys.has(`sku:${normalizeText(option.skuCode).toUpperCase()}`))

    const externalOptions = componentSkuOptions
      .map((option) => ({
        key: `external:${option.variantId}`,
        sourceType: 'external',
        ...option,
        productTypeLabel: getProductTypeLabel(option.productType),
        sourceLabel: 'SKU hiện có',
      }))
      .filter((option) => {
        const optionSku = normalizeText(option.skuCode).toUpperCase()
        return optionSku !== normalizeText(sku?.skuCode).toUpperCase()
          && String(option.variantId) !== String(sku?.variantId || sku?.id || '')
          && !selectedKeys.has(`variant:${option.variantId}`)
          && !selectedKeys.has(`sku:${optionSku}`)
      })

    return [...localOptions, ...externalOptions]
  }

  function addBomComponent(skuIndex, option) {
    if (!option) return
    let line = null
    if (option.sourceType === 'local') {
      const localSku = skuRows.find((sku) => sku.requestSkuKey === option.requestSkuKey)
      if (!localSku) return
      line = {
        materialId: EMPTY_GUID,
        materialName: row.name,
        materialUnitName: localSku.unitName || row.baseUnit,
        quantity: 1,
        componentRequestSkuKey: localSku.requestSkuKey,
        componentSkuCode: localSku.skuCode,
        componentVariantName: localSku.variantName || localSku.unitName,
        isRequiredBaseComponent: false,
      }
    } else {
      line = createBomLineFromComponentSku(option)
    }

    const nextSkuRows = skuRows.map((sku, currentIndex) => (
      currentIndex === skuIndex
        ? { ...sku, bomLines: [...(sku.bomLines ?? []), line] }
        : sku
    ))
    applySkuRows(row, nextSkuRows)
  }

  function updateBomLine(skuIndex, lineIndex, changes) {
    const nextSkuRows = skuRows.map((sku, currentIndex) => (
      currentIndex === skuIndex
        ? {
          ...sku,
          bomLines: (sku.bomLines ?? []).map((line, currentLineIndex) => (
            currentLineIndex === lineIndex && !line.isRequiredBaseComponent ? { ...line, ...changes } : line
          )),
        }
        : sku
    ))
    applySkuRows(row, nextSkuRows)
  }

  function removeBomLine(skuIndex, lineIndex) {
    const nextSkuRows = skuRows.map((sku, currentIndex) => (
      currentIndex === skuIndex
        ? { ...sku, bomLines: (sku.bomLines ?? []).filter((line, currentLineIndex) => line.isRequiredBaseComponent || currentLineIndex !== lineIndex) }
        : sku
    ))
    applySkuRows(row, nextSkuRows)
  }

  function updateAttribute(index, changes) {
    onChange({
      attributes: attributes.map((attribute, currentIndex) => (
        currentIndex === index ? { ...attribute, ...changes } : attribute
      )),
    })
  }

  function addAttribute() {
    const emptyAttribute = attributes.find((attribute) =>
      !normalizeAttributeName(attribute.attributeName) && !normalizeAttributeValue(attribute.value))
    if (emptyAttribute) {
      setPendingAttributeFocusKey(emptyAttribute.clientKey)
      return
    }

    const nextAttribute = createAttributeRow()
    setPendingAttributeFocusKey(nextAttribute.clientKey)
    onChange({ attributes: [...attributes, nextAttribute] })
  }

  function removeAttribute(index) {
    onChange({ attributes: attributes.filter((_, currentIndex) => currentIndex !== index) })
  }

  function usedAttributeKeysExcept(index) {
    return new Set(attributes
      .filter((_, currentIndex) => currentIndex !== index)
      .map((attribute) => getAttributeNameKey(attribute.attributeName))
      .filter(Boolean))
  }

  return (
    <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
      <div className="grid gap-3 md:grid-cols-4">
        <label className="text-xs font-semibold text-slate-500">
          Tên sản phẩm
          <input className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" value={row.name} onChange={(event) => updateProduct({ name: event.target.value })} />
        </label>
        <label className="text-xs font-semibold text-slate-500">
          Loại hàng
          <select
            className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
            value={row.productType}
            onChange={(event) => updateProduct({ productType: event.target.value, isSellable: getDefaultSellableByType(event.target.value) })}
          >
            {PRODUCT_TYPE_OPTIONS.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}
          </select>
        </label>
        <label className="text-xs font-semibold text-slate-500">
          Danh mục
          <select className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" value={row.categoryId} onChange={(event) => updateProduct({ categoryId: event.target.value })}>
            <option value="">Chọn danh mục</option>
            {categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}
          </select>
        </label>
        <label className="text-xs font-semibold text-slate-500">
          Đơn vị tồn kho
          <select className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" value={row.inventoryUnit} onChange={(event) => updateProduct({ inventoryUnit: event.target.value })}>
            {INVENTORY_UNIT_OPTIONS.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}
          </select>
        </label>
      </div>
      <label className="mt-3 block text-xs font-semibold text-slate-500">
        Mô tả
        <input
          className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"
          value={row.description || ''}
          onChange={(event) => updateProduct({ description: event.target.value })}
        />
      </label>

      <div className="mt-4 rounded-lg border border-slate-100 bg-slate-50 p-3">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <p className="text-xs font-bold uppercase tracking-wide text-slate-500">Quản lý đơn vị và SKU</p>
            <p className="text-xs text-slate-500">Mỗi đơn vị đóng gói là một SKU tồn kho riêng, không tự quy đổi tồn.</p>
          </div>
          <button type="button" className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-semibold" onClick={addSku}>+ Thêm đơn vị</button>
        </div>

        <div className="mt-3 space-y-3">
          {skuRows.map((sku, index) => (
            <div key={sku.requestSkuKey || index} className="rounded-lg border border-slate-200 bg-white p-3">
              <div className="grid gap-3 md:grid-cols-6">
                <label className="text-xs font-semibold text-slate-500">
                  {sku.isBaseUnitVariant ? 'Tên đơn vị cơ bản' : 'Tên đơn vị'}
                  <input className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" value={sku.unitName} onChange={(event) => updateSku(index, { unitName: event.target.value })} />
                </label>
                <label className="text-xs font-semibold text-slate-500">
                  Quy đổi
                  <input type="text" inputMode="numeric" pattern="[0-9]*" disabled={sku.isBaseUnitVariant} onKeyDown={preventNonIntegerKey} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm disabled:bg-slate-100" value={sku.conversionRate} onChange={(event) => updateSku(index, { conversionRate: event.target.value })} />
                </label>
                <label className="text-xs font-semibold text-slate-500 md:col-span-2">
                  Mã SKU tự sinh
                  <input className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 font-mono text-sm uppercase" value={sku.skuCode} onChange={(event) => updateSku(index, { skuCode: event.target.value.toUpperCase(), isAutoGeneratedSku: false })} />
                </label>
                <label className="text-xs font-semibold text-slate-500">
                  Giá bán
                  <VndCurrencyInput className="mt-1" value={sku.retailPrice} readOnly={!sku.isBaseUnitVariant} onChange={(value) => updateSku(index, { retailPrice: value })} />
                  {!sku.isBaseUnitVariant ? (
                    <span className="mt-1 block text-[11px] font-medium text-slate-400">
                      Tự động tính theo giá đơn vị cơ bản × quy đổi
                    </span>
                  ) : null}
                </label>
                <label className="text-xs font-semibold text-slate-500">
                  Giá vốn
                  <VndCurrencyInput className="mt-1" value={sku.costPrice} onChange={(value) => updateSku(index, { costPrice: value })} />
                </label>
              </div>
              <div className="mt-3 grid gap-3 md:grid-cols-6">
                <label className="text-xs font-semibold text-slate-500 md:col-span-2">
                  Barcode
                  <input className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" value={sku.barcode || ''} onChange={(event) => updateSku(index, { barcode: event.target.value })} />
                </label>
                <label className="flex items-center gap-2 pt-6 text-sm font-semibold text-slate-700">
                  <input type="checkbox" checked={sku.isSellable !== false} onChange={(event) => updateSku(index, { isSellable: event.target.checked })} />
                  Bán trực tiếp
                </label>
                <label className="flex items-center gap-2 pt-6 text-sm font-semibold text-slate-700">
                  <input type="radio" name={`${row.clientKey}-base-sku`} checked={Boolean(sku.isBaseUnitVariant)} onChange={() => markBaseSku(index)} />
                  Đơn vị cơ bản
                </label>
                <label className="text-xs font-semibold text-slate-500">
                  Tồn tối thiểu
                  <input type="number" min="0" className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" value={sku.minStock} onChange={(event) => updateSku(index, { minStock: event.target.value })} />
                </label>
                <label className="text-xs font-semibold text-slate-500">
                  Tồn tối đa
                  <input type="number" min="0" className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" value={sku.maxStock} onChange={(event) => updateSku(index, { maxStock: event.target.value })} />
                </label>
                <div className="flex items-end justify-end">
                  <button type="button" disabled={sku.isBaseUnitVariant} className="font-semibold text-rose-600 disabled:opacity-40" onClick={() => removeSku(index)}>Xóa</button>
                </div>
              </div>

              {isFinishedProduct ? (
                <div className="mt-3 rounded-lg border border-slate-100 bg-slate-50 p-3">
                  <div className="flex flex-wrap items-center justify-between gap-3">
                    <p className="text-xs font-bold uppercase tracking-wide text-slate-500">BOM cho SKU {sku.skuCode || index + 1}</p>
                    <SkuComponentCombobox options={getAvailableComponentOptions(index)} onSelect={(option) => addBomComponent(index, option)} />
                  </div>
                  {(sku.bomLines ?? []).length === 0 ? <p className="mt-3 text-xs text-slate-400">Chưa có component BOM.</p> : null}
                  {(sku.bomLines ?? []).length > 0 ? (
                    <div className="mt-3 overflow-x-auto">
                      <table className="min-w-full text-left text-xs">
                        <thead className="text-slate-500">
                          <tr>
                            <th className="py-2 pr-3">Component SKU</th>
                            <th className="py-2 pr-3">Định mức</th>
                            <th className="py-2 text-right">Thao tác</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-200">
                          {(sku.bomLines ?? []).map((line, lineIndex) => (
                            <tr key={`${line.componentVariantId || line.componentRequestSkuKey || line.materialId}-${lineIndex}`} className={line.isRequiredBaseComponent ? 'bg-emerald-50/45' : ''}>
                              <td className="py-2 pr-3">
                                <div className="flex flex-wrap items-center gap-2">
                                  <p className="font-semibold text-slate-700">{line.componentSkuCode || line.materialName || line.materialId}</p>
                                  {line.isRequiredBaseComponent ? (
                                    <span className="inline-flex items-center gap-1 rounded-full bg-emerald-100 px-2 py-0.5 text-[11px] font-bold text-emerald-700">
                                      <span className="material-symbols-outlined text-[14px]">lock</span>
                                      Tự động theo quy đổi
                                    </span>
                                  ) : null}
                                </div>
                                <p className="text-[11px] text-slate-400">{line.componentVariantName || line.materialName}</p>
                              </td>
                              <td className="py-2 pr-3">
                                <div className="flex items-center gap-2">
                                  <input type="text" inputMode="numeric" pattern="[0-9]*" disabled={line.isRequiredBaseComponent} onKeyDown={preventNonIntegerKey} className="w-28 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm disabled:border-emerald-100 disabled:bg-emerald-50 disabled:font-semibold disabled:text-emerald-800" value={line.quantity} onChange={(event) => updateBomLine(index, lineIndex, { quantity: event.target.value })} />
                                  <span className="text-slate-500">{line.materialUnitName || 'đơn vị'}</span>
                                </div>
                              </td>
                              <td className="py-2 text-right">
                                {line.isRequiredBaseComponent ? (
                                  <span className="text-xs font-semibold text-slate-400">Bắt buộc</span>
                                ) : (
                                  <button type="button" className="font-semibold text-rose-600" onClick={() => removeBomLine(index, lineIndex)}>Xóa</button>
                                )}
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  ) : null}
                </div>
              ) : null}
            </div>
          ))}
        </div>
      </div>

      <div className="mt-4 rounded-lg border border-slate-100 bg-white p-3">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <p className="text-xs font-bold uppercase tracking-wide text-slate-500">Thuộc tính bổ sung</p>
          <button type="button" className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold" onClick={addAttribute}>+ Thêm thuộc tính</button>
        </div>
        {attributes.length === 0 ? <p className="mt-3 text-xs text-slate-400">Chưa có thuộc tính bổ sung.</p> : null}
        <div className="mt-3 space-y-2">
          {attributes.map((attribute, index) => (
            <div key={attribute.clientKey || index} className="grid gap-2 md:grid-cols-[1fr_1fr_auto]">
              <AttributeNameCombobox
                value={attribute.attributeName}
                options={attributeNameOptions}
                usedKeys={usedAttributeKeysExcept(index)}
                autoFocus={pendingAttributeFocusKey === attribute.clientKey}
                onFocused={() => setPendingAttributeFocusKey(null)}
                onSelect={(selection) => updateAttribute(index, selection)}
              />
              <input
                className="rounded-lg border border-slate-200 px-3 py-2 text-sm"
                placeholder="Giá trị"
                value={attribute.value}
                onChange={(event) => updateAttribute(index, { value: event.target.value })}
              />
              <button type="button" className="font-semibold text-rose-600" onClick={() => removeAttribute(index)}>Xóa</button>
            </div>
          ))}
        </div>
      </div>

      <div className="mt-3 flex justify-end">
        <button type="button" disabled={!canRemove} onClick={onRemove} className="font-semibold text-rose-600 disabled:opacity-40">Xóa sản phẩm</button>
      </div>
    </div>
  )
}

export default function ProductApprovalsPage() {
  const session = useAuthSession()
  const admin = isSystemAdmin(session)
  const warehouse = isWarehouseRole(session)
  const fileInputRef = useRef(null)
  const [categories, setCategories] = useState([])
  const [materials, setMaterials] = useState([])
  const [attributeNames, setAttributeNames] = useState([])
  const [requests, setRequests] = useState([])
  const [isLoading, setIsLoading] = useState(true)
  const [isSaving, setIsSaving] = useState(false)
  const [activeRequestId, setActiveRequestId] = useState(null)
  const [title, setTitle] = useState('')
  const [warehouseNote, setWarehouseNote] = useState('')
  const [rows, setRows] = useState([createDraftProduct()])
  const [statusFilter, setStatusFilter] = useState('all')
  const [importPreview, setImportPreview] = useState(null)
  const [importMode, setImportMode] = useState('replace')
  const [isImporting, setIsImporting] = useState(false)
  const [isExporting, setIsExporting] = useState(false)
  const [isTemplateGenerating, setIsTemplateGenerating] = useState(false)

  const materialsById = useMemo(() => new Map(materials.map((material) => [String(material.id), material])), [materials])
  const attributeNameOptions = useMemo(() => buildAttributeNameOptions(attributeNames, rows), [attributeNames, rows])
  const attributeNameByKey = useMemo(() => buildAttributeNameLookup(attributeNameOptions), [attributeNameOptions])
  const hasCurrentDraftData = useMemo(() => hasMeaningfulProductCreationDraftData(rows), [rows])
  const importAppendErrors = useMemo(() => (
    importPreview && importMode === 'append'
      ? validateAppendProductCreationImport(rows, importPreview.rows, { getSkuRows, syncSkuRows })
      : []
  ), [importMode, importPreview, rows])
  const importBlockingErrors = useMemo(() => [
    ...(importPreview?.errors ?? []),
    ...importAppendErrors,
  ], [importAppendErrors, importPreview])

  const loadRequests = useCallback(async (nextStatus) => {
    setIsLoading(true)
    try {
      const result = await fetchProductCreationRequests({ status: nextStatus, page: 1, pageSize: 50 })
      setRequests(result.items)
    } catch (error) {
      showError(error.message)
    } finally {
      setIsLoading(false)
    }
  }, [])

  useEffect(() => {
    let cancelled = false
    const timer = window.setTimeout(() => {
      Promise.all([
        fetchCategories({ isDeleted: false }),
        searchMaterials('', 100),
        fetchAttributeNames().catch((error) => {
          showError(`Không tải được danh sách thuộc tính: ${error.message}`)
          return []
        }),
        fetchProductCreationRequests({ status: 'all', page: 1, pageSize: 50 }),
      ])
        .then(([categoryItems, materialItems, attributeNameItems, requestResult]) => {
          if (cancelled) return
          setCategories(categoryItems)
          setMaterials(materialItems)
          setAttributeNames(attributeNameItems)
          setRequests(requestResult.items)
        })
        .catch((error) => showError(error.message))
        .finally(() => {
          if (!cancelled) setIsLoading(false)
        })
    }, 0)

    return () => {
      cancelled = true
      window.clearTimeout(timer)
    }
  }, [])

  function updateRow(index, changes) {
    setRows((current) => current.map((row, rowIndex) => (rowIndex === index ? { ...row, ...changes } : row)))
  }

  function resetForm() {
    setActiveRequestId(null)
    setTitle('')
    setWarehouseNote('')
    setRows([createDraftProduct()])
    setImportPreview(null)
    setImportMode('replace')
  }

  function loadIntoForm(request) {
    setActiveRequestId(request.id)
    setTitle(request.title)
    setWarehouseNote(request.warehouseNote || '')
    setRows(request.items.length ? request.items.map((item) => fromProductSnapshot(item, materialsById)) : [createDraftProduct()])
    setImportPreview(null)
    setImportMode('replace')
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  async function saveDraft({ showToast = true } = {}) {
    const errors = validateForm(title, rows)
    if (errors.length) {
      showError(errors[0])
      return null
    }

    setIsSaving(true)
    try {
      const payload = { title, warehouseNote, items: rows.map((row) => ({ clientKey: row.clientKey, product: toProductPayload(row) })) }
      const saved = activeRequestId
        ? await updateProductCreationRequest(activeRequestId, payload)
        : await createProductCreationRequest(payload)
      setActiveRequestId(saved.id)
      if (showToast) showSuccess('Đã lưu yêu cầu tạo hàng hóa.')
      await loadRequests(statusFilter)
      return saved
    } catch (error) {
      showError(error.message)
      return null
    } finally {
      setIsSaving(false)
    }
  }

  async function handleSubmit() {
    const saved = await saveDraft({ showToast: false })
    if (!saved?.id) return

    setIsSaving(true)
    try {
      await submitProductCreationRequest(saved.id, warehouseNote)
      showSuccess('Đã gửi yêu cầu cho Admin duyệt.')
      resetForm()
      await loadRequests(statusFilter)
    } catch (error) {
      showError(error.message)
    } finally {
      setIsSaving(false)
    }
  }

  async function handleDecision(request, action) {
    const reason = action === 'approve' ? '' : window.prompt(action === 'reject' ? 'Nhập lý do từ chối:' : 'Nhập lý do hủy:')
    if (action !== 'approve' && !String(reason || '').trim()) return

    setIsSaving(true)
    try {
      if (action === 'approve') await approveProductCreationRequest(request.id, '')
      if (action === 'reject') await rejectProductCreationRequest(request.id, reason, '')
      if (action === 'cancel') await cancelProductCreationRequest(request.id, reason, '')
      showSuccess('Đã cập nhật yêu cầu.')
      await loadRequests(statusFilter)
    } catch (error) {
      showError(error.message)
    } finally {
      setIsSaving(false)
    }
  }

  async function loadExcelReferenceData() {
    const [categoryResult, materialResult, attributeNameResult] = await Promise.allSettled([
      fetchCategories({ isDeleted: false }),
      searchMaterials('', 500),
      fetchAttributeNames(),
    ])

    const categoryReference = buildReferenceLoadEntry('categories', categoryResult, categories)
    const materialReference = buildReferenceLoadEntry('componentSkus', materialResult, materials)
    const attributeNameReference = buildReferenceLoadEntry('attributeNames', attributeNameResult, attributeNames)

    const categoryItems = categoryReference.items
    const materialItems = materialReference.items
    const attributeNameItems = attributeNameReference.items
    const failures = [
      categoryReference.failure,
      materialReference.failure,
      attributeNameReference.failure,
    ].filter(Boolean)
    const referenceLoadStatuses = [
      categoryReference.status,
      materialReference.status,
      attributeNameReference.status,
    ]

    setCategories(categoryItems)
    setMaterials(materialItems)
    setAttributeNames(attributeNameItems)

    return {
      categoryItems,
      materialItems,
      attributeNameItems,
      failures,
      referenceLoadStatuses,
    }
  }

  async function downloadTemplate() {
    setIsTemplateGenerating(true)
    try {
      const { categoryItems, materialItems, attributeNameItems, failures, referenceLoadStatuses } = await loadExcelReferenceData()
      await downloadOfficialProductCreationTemplate({
        categories: categoryItems,
        materials: materialItems,
        attributeNameOptions: buildAttributeNameOptions(attributeNameItems, []),
        referenceLoadStatuses,
      })
      showReferenceWarningToast(failures)
    } catch {
      showError('Không tạo được file mẫu Excel. Vui lòng thử lại.')
    } finally {
      setIsTemplateGenerating(false)
    }
  }

  async function exportCurrentDraft() {
    const errors = validateForm(title || 'Yêu cầu tạo hàng hóa', rows)
    if (errors.length) {
      showError(errors[0])
      return
    }

    setIsExporting(true)
    try {
      const { categoryItems, materialItems, attributeNameItems, failures, referenceLoadStatuses } = await loadExcelReferenceData()
      await exportProductCreationDraftToTemplate({
        rows,
        categories: categoryItems,
        materials: materialItems,
        attributeNameOptions: buildAttributeNameOptions(attributeNameItems, rows),
        referenceLoadStatuses,
        filename: formatProductCreationDraftExportFilename(),
        helpers: {
          getSkuRows,
          syncSkuRows,
          getSubmittableAttributes,
          moneyOrNull,
        },
      })
      if (failures.length) {
        showReferenceWarningToast(failures)
      } else {
        showSuccess('Đã export bản nháp theo file mẫu chính thức.')
      }
    } catch (error) {
      showError(error.message || 'Không thể export file Excel.')
    } finally {
      setIsExporting(false)
    }
  }

  async function handleImportFile(event) {
    const file = event.target.files?.[0]
    event.target.value = ''
    if (!file) return

    setIsImporting(true)
    try {
      const preview = await parseOfficialProductCreationFile(file, {
        categories,
        materials,
        attributeNameByKey,
        createDraftProduct,
        createAttributeRow,
        syncLegacySkuFields,
      })
      setImportPreview(preview)
      setImportMode(hasCurrentDraftData ? 'replace' : 'replace')
      if (preview.errors.length) {
        showError(preview.errors[0])
      } else {
        showSuccess('Đã đọc file Excel. Kiểm tra preview trước khi áp dụng vào bản nháp.')
      }
    } catch (error) {
      showError(error.message || 'Không thể đọc file Excel.')
    } finally {
      setIsImporting(false)
    }
  }

  function applyImportPreview() {
    if (!importPreview) return
    if (importBlockingErrors.length) {
      showError(importBlockingErrors[0])
      return
    }

    const nextRows = importMode === 'append'
      ? [...rows, ...importPreview.rows]
      : importPreview.rows

    setRows(nextRows.length ? nextRows : [createDraftProduct()])
    if (!title.trim()) setTitle(importPreview.suggestedTitle || importPreview.sourceFilename?.replace(/\.xlsx$/i, '') || '')
    setImportPreview(null)
    setImportMode('replace')
    showSuccess('Đã áp dụng dữ liệu import vào bản nháp.')
  }

  return (
    <PageShell
      title="Yêu cầu tạo hàng hóa"
      description="Warehouse tạo yêu cầu nhiều sản phẩm, Admin duyệt và hệ thống tạo Product/SKU/BOM atomically."
      actions={(
        <select className="rounded-lg border border-slate-200 px-3 py-2 text-sm" value={statusFilter} onChange={(event) => { setStatusFilter(event.target.value); loadRequests(event.target.value) }}>
          <option value="all">Tất cả</option>
          <option value="Draft">Nháp</option>
          <option value="PendingApproval">Chờ duyệt</option>
          <option value="Rejected">Bị từ chối</option>
          <option value="Completed">Đã tạo</option>
          <option value="Cancelled">Đã hủy</option>
        </select>
      )}
    >
      {warehouse ? (
        <section className="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
          <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
            <div>
              <h2 className="text-base font-bold text-slate-900">{activeRequestId ? 'Sửa yêu cầu' : 'Tạo biên bản yêu cầu thêm sản phẩm kho mới'}</h2>
              <p className="text-sm text-slate-500">Không dùng approval code. Admin chỉ duyệt/từ chối nội dung Warehouse gửi.</p>
            </div>
            <div className="flex flex-wrap gap-2">
              <input ref={fileInputRef} type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" className="hidden" onChange={handleImportFile} />
              <button type="button" disabled={isTemplateGenerating} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold disabled:opacity-50" onClick={downloadTemplate}>{isTemplateGenerating ? 'Đang tạo file mẫu...' : 'Tải file mẫu'}</button>
              <button type="button" disabled={isImporting} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold disabled:opacity-50" onClick={() => fileInputRef.current?.click()}>{isImporting ? 'Đang đọc...' : 'Import Excel'}</button>
              <button type="button" disabled={isExporting} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold disabled:opacity-50" onClick={exportCurrentDraft}>{isExporting ? 'Đang export...' : 'Export Excel'}</button>
              {activeRequestId ? <button type="button" className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold" onClick={resetForm}>Tạo yêu cầu khác</button> : null}
            </div>
          </div>

          {importPreview ? (
            <div className="mb-4 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm">
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div>
                  <p className="font-bold text-slate-900">Preview import Excel</p>
                  <p className="mt-1 text-xs text-slate-500">
                    File: <span className="font-semibold text-slate-700">{importPreview.sourceFilename || '—'}</span>
                    <span className="mx-2">•</span>
                    Sheet: <span className="font-semibold text-slate-700">{importPreview.sheetName || '—'}</span>
                  </p>
                  <p className="mt-1 text-xs text-slate-500">File mẫu chính thức: {PRODUCT_CREATION_TEMPLATE_FILENAME}</p>
                </div>
                <button type="button" className="font-semibold text-slate-500 hover:text-slate-700" onClick={() => setImportPreview(null)}>Đóng</button>
              </div>

              <div className="mt-3 grid gap-2 sm:grid-cols-3 lg:grid-cols-6">
                <div className="rounded-lg bg-white px-3 py-2">
                  <p className="text-[11px] font-bold uppercase text-slate-400">Sản phẩm</p>
                  <p className="text-lg font-bold text-slate-900">{importPreview.counts.products}</p>
                </div>
                <div className="rounded-lg bg-white px-3 py-2">
                  <p className="text-[11px] font-bold uppercase text-slate-400">SKU</p>
                  <p className="text-lg font-bold text-slate-900">{importPreview.counts.skus}</p>
                </div>
                <div className="rounded-lg bg-white px-3 py-2">
                  <p className="text-[11px] font-bold uppercase text-slate-400">Thuộc tính</p>
                  <p className="text-lg font-bold text-slate-900">{importPreview.counts.attributes}</p>
                </div>
                <div className="rounded-lg bg-white px-3 py-2">
                  <p className="text-[11px] font-bold uppercase text-slate-400">BOM component</p>
                  <p className="text-lg font-bold text-slate-900">{importPreview.counts.manualBomLines}</p>
                </div>
                <div className="rounded-lg bg-white px-3 py-2">
                  <p className="text-[11px] font-bold uppercase text-slate-400">Cảnh báo</p>
                  <p className="text-lg font-bold text-amber-700">{importPreview.warnings.length}</p>
                </div>
                <div className="rounded-lg bg-white px-3 py-2">
                  <p className="text-[11px] font-bold uppercase text-slate-400">Lỗi</p>
                  <p className="text-lg font-bold text-rose-700">{importBlockingErrors.length}</p>
                </div>
              </div>

              {hasCurrentDraftData && importPreview.errors.length === 0 ? (
                <div className="mt-3 flex flex-wrap gap-3 rounded-lg border border-slate-200 bg-white p-3">
                  <label className="flex items-center gap-2 font-semibold text-slate-700">
                    <input type="radio" name="product-import-mode" checked={importMode === 'replace'} onChange={() => setImportMode('replace')} />
                    Thay thế dữ liệu hiện tại
                  </label>
                  <label className="flex items-center gap-2 font-semibold text-slate-700">
                    <input type="radio" name="product-import-mode" checked={importMode === 'append'} onChange={() => setImportMode('append')} />
                    Nối thêm vào bản nháp
                  </label>
                </div>
              ) : null}

              {importPreview.warnings.length ? (
                <div className="mt-3 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-amber-800">
                  <p className="font-semibold">Cảnh báo</p>
                  <ul className="mt-2 list-disc space-y-1 pl-5">
                    {importPreview.warnings.slice(0, 8).map((warning) => <li key={warning}>{warning}</li>)}
                  </ul>
                </div>
              ) : null}

              {importBlockingErrors.length ? (
                <div className="mt-3 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-rose-700">
                  <p className="font-semibold">Import Excel chưa hợp lệ</p>
                  <ul className="mt-2 list-disc space-y-1 pl-5">
                    {importBlockingErrors.slice(0, 12).map((error) => <li key={error}>{error}</li>)}
                  </ul>
                </div>
              ) : null}

              <div className="mt-3 flex flex-wrap justify-end gap-2">
                <button type="button" className="rounded-lg border border-slate-200 bg-white px-4 py-2 font-semibold" onClick={() => setImportPreview(null)}>Hủy</button>
                <button
                  type="button"
                  disabled={importBlockingErrors.length > 0}
                  className="rounded-lg bg-[#356647] px-4 py-2 font-semibold text-white disabled:opacity-50"
                  onClick={applyImportPreview}
                >
                  Áp dụng vào bản nháp
                </button>
              </div>
            </div>
          ) : null}

          <div className="grid gap-3 md:grid-cols-2">
            <label className="text-xs font-semibold text-slate-500">
              Tiêu đề
              <input className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" value={title} onChange={(event) => setTitle(event.target.value)} />
            </label>
            <label className="text-xs font-semibold text-slate-500">
              Ghi chú Warehouse
              <input className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" value={warehouseNote} onChange={(event) => setWarehouseNote(event.target.value)} />
            </label>
          </div>
          <div className="mt-4 space-y-4">
            {rows.map((row, index) => (
              <ProductRow
                key={row.clientKey}
                row={row}
                categories={categories}
                materials={materials}
                attributeNameOptions={attributeNameOptions}
                onChange={(changes) => updateRow(index, changes)}
                onRemove={() => setRows((current) => current.filter((_, rowIndex) => rowIndex !== index))}
                canRemove={rows.length > 1}
              />
            ))}
          </div>
          <div className="mt-4 flex flex-wrap justify-end gap-2">
            <button type="button" className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold" onClick={() => setRows((current) => [...current, createDraftProduct()])}>Thêm sản phẩm</button>
            <button type="button" disabled={isSaving} className="rounded-lg bg-slate-100 px-4 py-2 text-sm font-semibold text-slate-700" onClick={() => saveDraft()}>{isSaving ? 'Đang lưu...' : 'Lưu nháp'}</button>
            <button type="button" disabled={isSaving} className="rounded-lg bg-[#356647] px-4 py-2 text-sm font-semibold text-white" onClick={handleSubmit}>{isSaving ? 'Đang gửi...' : 'Gửi Admin duyệt'}</button>
          </div>
        </section>
      ) : null}

      <section className="rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div className="border-b border-slate-100 px-5 py-4">
          <h2 className="text-base font-bold text-slate-900">{admin ? 'Yêu cầu chờ xử lý' : 'Yêu cầu tạo hàng hóa'}</h2>
        </div>
        <div className="overflow-x-auto">
          <table className="min-w-full text-left text-sm">
            <thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500">
              <tr>
                <th className="px-4 py-3">Mã yêu cầu</th>
                <th className="px-4 py-3">Tiêu đề</th>
                <th className="px-4 py-3">Sản phẩm</th>
                <th className="px-4 py-3">Trạng thái</th>
                <th className="px-4 py-3">Revision</th>
                <th className="px-4 py-3">Thời gian</th>
                <th className="px-4 py-3 text-right">Thao tác</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {isLoading ? (
                <tr><td colSpan={7} className="px-4 py-8 text-center text-slate-400">Đang tải...</td></tr>
              ) : null}
              {!isLoading && requests.length === 0 ? (
                <tr><td colSpan={7} className="px-4 py-8 text-center text-slate-400">Chưa có yêu cầu tạo hàng hóa.</td></tr>
              ) : null}
              {requests.map((request) => (
                <tr key={request.id} className="align-top">
                  <td className="px-4 py-3 font-mono text-xs text-[#356647]">{request.requestCode}</td>
                  <td className="px-4 py-3 font-semibold text-slate-800">
                    <p>{request.title}</p>
                    {request.createdByName ? <p className="mt-1 text-xs font-normal text-slate-500">Người tạo: {request.createdByName}</p> : null}
                    {request.rejectReason ? <p className="mt-1 text-xs text-rose-600">Từ chối: {request.rejectReason}</p> : null}
                  </td>
                  <td className="px-4 py-3">
                    <div className="space-y-1">
                      {request.items.map((item) => {
                        const priceSummary = requestItemPriceSummary(item)
                        const snapshotVariants = item.productSnapshot?.variants ?? item.ProductSnapshot?.Variants ?? []
                        const snapshotAttributes = item.productSnapshot?.attributes ?? item.ProductSnapshot?.Attributes ?? []
                        return (
                          <div key={item.clientKey} className="text-xs text-slate-600">
                            <p>
                              <span className="font-semibold text-slate-800">{item.productName}</span> · {getProductTypeLabel(item.productType)} · {item.variantCount} SKU · {item.bomLineCount} BOM
                            </p>
                            {priceSummary ? <p className="mt-0.5 text-[11px] text-slate-500">{priceSummary}</p> : null}
                            {Array.isArray(snapshotAttributes) && snapshotAttributes.length > 0 ? (
                              <div className="mt-1 flex flex-wrap gap-1">
                                {snapshotAttributes.map((attribute, attributeIndex) => (
                                  <span key={`${item.clientKey}-attr-${attributeIndex}`} className="inline-flex rounded-full bg-[#f0eee6] px-2 py-0.5 text-[11px] font-semibold text-slate-600">
                                    {attribute.attributeName || attribute.AttributeName}: {attribute.value || attribute.Value}
                                  </span>
                                ))}
                              </div>
                            ) : null}
                            {Array.isArray(snapshotVariants) && snapshotVariants.length > 0 ? (
                              <div className="mt-1 space-y-1 text-[11px] text-slate-500">
                                {snapshotVariants.map((variant) => {
                                  const variantSkuCode = variant.skuCode ?? variant.SkuCode ?? ''
                                  const bomLines = variant.bomLines ?? variant.BomLines ?? []
                                  return (
                                    <div key={variant.requestSkuKey || variant.RequestSkuKey || variantSkuCode}>
                                      <span className="font-mono font-semibold text-[#356647]">{variantSkuCode}</span>
                                      {bomLines.map((line, lineIndex) => (
                                        <span key={`${variantSkuCode}-${lineIndex}`} className="ml-2 inline-flex items-center gap-1 rounded-full bg-slate-100 px-2 py-0.5">
                                          {line.componentSkuCode || line.ComponentSkuCode || line.materialName || line.MaterialName || line.materialId || line.MaterialId} x{line.quantity ?? line.Quantity}
                                          {line.isRequiredBaseComponent || line.IsRequiredBaseComponent ? <span className="font-semibold text-emerald-700">Tự động theo quy đổi</span> : null}
                                        </span>
                                      ))}
                                    </div>
                                  )
                                })}
                              </div>
                            ) : null}
                          </div>
                        )
                      })}
                    </div>
                  </td>
                  <td className="px-4 py-3">{statusLabel(request.status)}</td>
                  <td className="px-4 py-3">{request.revisionNumber}</td>
                  <td className="px-4 py-3 text-xs text-slate-500">{formatDateTimeVN(request.submittedAt || request.createdAt)}</td>
                  <td className="px-4 py-3 text-right">
                    <div className="flex justify-end gap-2">
                      {warehouse && ['Draft', 'Rejected'].includes(request.status) ? (
                        <button type="button" className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold" onClick={() => loadIntoForm(request)}>Sửa</button>
                      ) : null}
                      {admin && request.status === 'PendingApproval' ? (
                        <>
                          <button type="button" className="rounded-lg bg-[#356647] px-3 py-1.5 text-xs font-semibold text-white" onClick={() => handleDecision(request, 'approve')}>Duyệt</button>
                          <button type="button" className="rounded-lg bg-amber-100 px-3 py-1.5 text-xs font-semibold text-amber-700" onClick={() => handleDecision(request, 'reject')}>Từ chối</button>
                          <button type="button" className="rounded-lg bg-rose-100 px-3 py-1.5 text-xs font-semibold text-rose-700" onClick={() => handleDecision(request, 'cancel')}>Hủy</button>
                        </>
                      ) : null}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </PageShell>
  )
}
