// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using OrderService.Infrastructure.Data;

#nullable disable

namespace OrderService.Infrastructure.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260613170000_AddOrderDetailReportingColumns")]
    partial class AddOrderDetailReportingColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
