// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using OrderService.Infrastructure.Data;

#nullable disable

namespace OrderService.Infrastructure.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260613110000_AddPromotionCustomerTierScopes")]
    partial class AddPromotionCustomerTierScopes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
