import { apiRequestAuth, toPagedResult } from '../../../lib/apiClient.js'

export function mapProductionOrderLine(row) {
  if (!row) return null
  return {
    id: row.id ?? row.Id,
    materialSkuId: row.materialSkuId ?? row.MaterialSkuId,
    materialSkuCode: row.materialSkuCode ?? row.MaterialSkuCode ?? '',
    materialSnapshotName: row.materialSnapshotName ?? row.MaterialSnapshotName ?? '',
    plannedQuantity: Number(row.plannedQuantity ?? row.PlannedQuantity ?? 0),
  }
}

export function mapProductionOrderOutputLine(row) {
  if (!row) return null
  const plannedQuantity = Number(row.plannedQuantity ?? row.PlannedQuantity ?? row.quantity ?? row.Quantity ?? 0)
  return {
    id: row.id ?? row.Id,
    finishedSkuId: row.finishedSkuId ?? row.FinishedSkuId,
    finishedSkuCode: row.finishedSkuCode ?? row.FinishedSkuCode ?? '',
    finishedSkuSnapshotName: row.finishedSkuSnapshotName ?? row.FinishedSkuSnapshotName ?? '',
    plannedQuantity,
    expiresAt: row.expiresAt ?? row.ExpiresAt ?? null,
    destinationLocation: row.destinationLocation ?? row.DestinationLocation ?? 'Warehouse',
    warehouseBatchId: row.warehouseBatchId ?? row.WarehouseBatchId ?? null,
    warehouseBatchLotCode: row.warehouseBatchLotCode ?? row.WarehouseBatchLotCode ?? null,
  }
}

export function mapProductionOrder(row) {
  if (!row) return null
  const outputLines = (row.outputLines ?? row.OutputLines ?? []).map(mapProductionOrderOutputLine).filter(Boolean)
  return {
    id: row.id ?? row.Id,
    productionCode: row.productionCode ?? row.ProductionCode ?? '',
    note: row.note ?? row.Note ?? null,
    status: row.status ?? row.Status ?? 'Draft',
    createdBy: row.createdBy ?? row.CreatedBy,
    createdByName: row.createdByName ?? row.CreatedByName ?? null,
    createdByRoleName: row.createdByRoleName ?? row.CreatedByRoleName ?? null,
    createdAt: row.createdAt ?? row.CreatedAt ?? null,
    updatedAt: row.updatedAt ?? row.UpdatedAt ?? null,
    submittedBy: row.submittedBy ?? row.SubmittedBy ?? null,
    submittedAt: row.submittedAt ?? row.SubmittedAt ?? null,
    reviewedBy: row.reviewedBy ?? row.ReviewedBy ?? null,
    reviewedByName: row.reviewedByName ?? row.ReviewedByName ?? null,
    reviewedByRoleName: row.reviewedByRoleName ?? row.ReviewedByRoleName ?? null,
    reviewedAt: row.reviewedAt ?? row.ReviewedAt ?? null,
    reviewNote: row.reviewNote ?? row.ReviewNote ?? null,
    completedAt: row.completedAt ?? row.CompletedAt ?? null,
    isAutoGeneratedForShelfReplenishment: Boolean(
      row.isAutoGeneratedForShelfReplenishment ?? row.IsAutoGeneratedForShelfReplenishment,
    ),
    sourceStockAdjustmentRequestId:
      row.sourceStockAdjustmentRequestId ?? row.SourceStockAdjustmentRequestId ?? null,
    sourceStockAdjustmentRequestItemId:
      row.sourceStockAdjustmentRequestItemId ?? row.SourceStockAdjustmentRequestItemId ?? null,
    lines: (row.lines ?? row.Lines ?? []).map(mapProductionOrderLine).filter(Boolean),
    outputLines,
  }
}

export const PRODUCTION_STATUS_LABEL = {
  Draft: 'Chờ hoàn thành',
  PendingApproval: 'Chờ hoàn thành',
  Approved: 'Chờ hoàn thành',
  Completed: 'Hoàn thành',
  Rejected: 'Bị từ chối',
  Cancelled: 'Đã hủy',
}

export const PRODUCTION_STATUS_CLASS = {
  Draft: 'bg-amber-50 text-amber-700 border border-amber-200',
  PendingApproval: 'bg-amber-50 text-amber-700 border border-amber-200',
  Approved: 'bg-amber-50 text-amber-700 border border-amber-200',
  Completed: 'bg-green-50 text-green-700 border border-green-200',
  Rejected: 'bg-red-50 text-red-700 border border-red-200',
  Cancelled: 'bg-slate-100 text-slate-500 border border-slate-200',
}

export async function fetchProductionOrders({ status, page = 1, pageSize = 20 } = {}) {
  const params = new URLSearchParams({ page: String(page), pageSize: String(pageSize) })
  if (status) params.set('status', status)
  const data = await apiRequestAuth(`/api/v1/inventory/production-orders?${params}`, { method: 'GET' })
  const paged = toPagedResult(data)
  return {
    ...paged,
    items: paged.items.map(mapProductionOrder).filter(Boolean),
  }
}

export async function fetchProductionOrderById(id) {
  const data = await apiRequestAuth(`/api/v1/inventory/production-orders/${id}`, { method: 'GET' })
  return mapProductionOrder(data)
}

export async function createProductionOrder(payload) {
  const outputLines = payload.outputLines ?? payload.outputs ?? []
  const data = await apiRequestAuth('/api/v1/inventory/production-orders', {
    method: 'POST',
    body: JSON.stringify({
      note: payload.note?.trim() || null,
      outputLines: outputLines.map((output) => ({
        finishedSkuId: output.finishedSkuId,
        finishedSkuCode: output.finishedSkuCode,
        finishedSkuSnapshotName: output.finishedSkuSnapshotName,
        plannedQuantity: Number(output.plannedQuantity ?? output.quantity),
        expiresAt: output.expiresAt || null,
        destinationLocation: output.destinationLocation || 'Warehouse',
      })),
      lines: (payload.lines ?? []).map((l) => ({
        materialSkuId: l.materialSkuId,
        materialSkuCode: l.materialSkuCode,
        materialSnapshotName: l.materialSnapshotName,
        plannedQuantity: Number(l.plannedQuantity),
      })),
    }),
  })
  return mapProductionOrder(data)
}

export async function submitProductionOrder(id) {
  const data = await apiRequestAuth(`/api/v1/inventory/production-orders/${id}/submit`, { method: 'POST' })
  return mapProductionOrder(data)
}

export async function approveProductionOrder(id, reason = '') {
  const data = await apiRequestAuth(`/api/v1/inventory/production-orders/${id}/approve`, {
    method: 'POST',
    body: JSON.stringify({ reason: reason?.trim() || null }),
  })
  return mapProductionOrder(data)
}

export async function rejectProductionOrder(id, reason) {
  const data = await apiRequestAuth(`/api/v1/inventory/production-orders/${id}/reject`, {
    method: 'POST',
    body: JSON.stringify({ reason: reason?.trim() || '' }),
  })
  return mapProductionOrder(data)
}

export async function completeProductionOrder(id) {
  const data = await apiRequestAuth(`/api/v1/inventory/production-orders/${id}/complete`, { method: 'POST' })
  return mapProductionOrder(data)
}

export async function previewProductionOrderAvailability(id) {
  const data = await apiRequestAuth(`/api/v1/inventory/production-orders/${id}/availability`, { method: 'GET' })
  const items = (data.items ?? data.Items ?? []).map((item) => ({
    materialSkuId: item.materialSkuId ?? item.MaterialSkuId,
    materialSkuCode: item.materialSkuCode ?? item.MaterialSkuCode ?? '',
    materialName: item.materialName ?? item.MaterialName ?? '',
    requiredQuantity: Number(item.requiredQuantity ?? item.RequiredQuantity ?? 0),
    availableQuantity: Number(item.availableQuantity ?? item.AvailableQuantity ?? 0),
    shortageQuantity: Number(item.shortageQuantity ?? item.ShortageQuantity ?? 0),
  }))
  return { canComplete: Boolean(data.canComplete ?? data.CanComplete), items }
}

export async function cancelProductionOrder(id, reason) {
  const data = await apiRequestAuth(`/api/v1/inventory/production-orders/${id}/cancel`, {
    method: 'POST',
    body: JSON.stringify({ reason: reason?.trim() || '' }),
  })
  return mapProductionOrder(data)
}
