using InventoryService.Domain.Enums;

namespace InventoryService.Domain.Entities;

public class ProductionOrder
{
    public Guid Id { get; set; }
    public string ProductionCode { get; set; } = string.Empty;
    public string? Note { get; set; }
    public ProductionOrderStatus Status { get; set; } = ProductionOrderStatus.Draft;
    public Guid CreatedBy { get; set; }
    public string? CreatedByName { get; set; }
    public string? CreatedByRoleName { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
    public Guid? SubmittedBy { get; set; }
    public DateTime? SubmittedAt { get; set; }
    public Guid? ReviewedBy { get; set; }
    public string? ReviewedByName { get; set; }
    public string? ReviewedByRoleName { get; set; }
    public DateTime? ReviewedAt { get; set; }
    public string? ReviewNote { get; set; }
    public DateTime? CompletedAt { get; set; }
    public bool IsAutoGeneratedForShelfReplenishment { get; set; }
    public Guid? SourceStockAdjustmentRequestId { get; set; }
    public Guid? SourceStockAdjustmentRequestItemId { get; set; }
    public ICollection<ProductionOrderLine> Lines { get; set; } = [];
    public ICollection<ProductionOrderOutputLine> OutputLines { get; set; } = [];
}
