namespace ProductService.Application.DTOs.Responses;

public record ProductImageResponse(
    Guid Id,
    Guid ProductId,
    string ImageUrl,
    string? AltText,
    int SortOrder,
    bool IsThumbnail);

public record ProductUnitResponse(
    Guid Id,
    Guid ProductId,
    Guid? VariantId,
    string UnitName,
    decimal ConversionRate,
    decimal? Price,
    string? Barcode,
    bool IsDirectSell,
    bool IsBaseUnit);

public record BomLineResponse(
    Guid MaterialId,
    string MaterialName,
    string? MaterialUnitName,
    decimal Quantity,
    Guid? ComponentVariantId = null,
    string? ComponentSkuCode = null,
    string? ComponentVariantName = null,
    bool IsRequiredBaseComponent = false);

public record ProductVariantResponse(
    Guid Id,
    Guid ProductId,
    string SkuCode,
    string? Barcode,
    string VariantName,
    string OptionValuesJson,
    decimal CostPrice,
    decimal RetailPrice,
    int? MinStock,
    int? MaxStock,
    bool IsSellable,
    bool AllowRewardPoints,
    bool IsActive,
    string? ImageUrl,
    string? UnitName,
    decimal ConversionRate,
    Guid? BaseVariantId,
    bool IsBaseUnitVariant,
    bool IsAutoGeneratedSku,
    bool IsPurchasable,
    bool CanBeBomComponent,
    bool CanUseInCustom,
    bool CanHaveBom,
    bool HasBom,
    int BomLineCount,
    List<ProductUnitResponse> Units,
    List<BomLineResponse> BomLines);
