namespace ProductService.Application.DTOs.Responses;

public record ProductResponse(
    Guid Id,
    int CategoryId,
    string CategoryName,
    string Name,
    string? Origin,
    string? FlavorProfile,
    string? BrewingGuide,
    string? Description,
    string BaseUnit,
    string InventoryUnit,
    decimal? WeightValue,
    string? WeightUnit,
    bool IsVariantParent,
    bool IsActive,
    bool IsDeleted,
    DateTime CreatedAt,
    DateTime? SyncedToStoreAt,
    string ProductType,
    List<ProductSkuResponse> Skus,
    List<ProductImageResponse> Images,
    List<ProductUnitResponse> Units,
    List<ProductVariantResponse> Variants);
