using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProductService.Infrastructure.Data;

#nullable disable

namespace ProductService.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260719120000_AddSkuUnitBomComponentAndProductAttributes")]
    public partial class AddSkuUnitBomComponentAndProductAttributes : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "BaseVariantId",
                table: "ProductVariants",
                type: "char(36)",
                nullable: true,
                collation: "ascii_general_ci");

            migrationBuilder.AddColumn<decimal>(
                name: "ConversionRate",
                table: "ProductVariants",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 1m);

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGeneratedSku",
                table: "ProductVariants",
                type: "tinyint(1)",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsBaseUnitVariant",
                table: "ProductVariants",
                type: "tinyint(1)",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "UnitName",
                table: "ProductVariants",
                type: "varchar(100)",
                maxLength: 100,
                nullable: true)
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.AddColumn<Guid>(
                name: "ComponentVariantId",
                table: "ProductVariantBomLines",
                type: "char(36)",
                nullable: true,
                collation: "ascii_general_ci");

            migrationBuilder.CreateTable(
                name: "ProductAttributeValues",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "char(36)", nullable: false, collation: "ascii_general_ci"),
                    ProductId = table.Column<Guid>(type: "char(36)", nullable: false, collation: "ascii_general_ci"),
                    AttributeNameId = table.Column<int>(type: "int", nullable: true),
                    AttributeName = table.Column<string>(type: "varchar(100)", maxLength: 100, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    Value = table.Column<string>(type: "varchar(500)", maxLength: 500, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    CreatedAt = table.Column<DateTime>(type: "datetime(6)", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "datetime(6)", nullable: true),
                    IsDeleted = table.Column<bool>(type: "tinyint(1)", nullable: false, defaultValue: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ProductAttributeValues", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ProductAttributeValues_AttributeNames_AttributeNameId",
                        column: x => x.AttributeNameId,
                        principalTable: "AttributeNames",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.SetNull);
                    table.ForeignKey(
                        name: "FK_ProductAttributeValues_Products_ProductId",
                        column: x => x.ProductId,
                        principalTable: "Products",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.Sql("""
                UPDATE ProductVariants pv
                JOIN Products p ON p.Id = pv.ProductId
                SET pv.UnitName = COALESCE(NULLIF(pv.UnitName, ''), NULLIF(p.BaseUnit, ''), NULLIF(pv.VariantName, ''), 'unit'),
                    pv.ConversionRate = 1,
                    pv.IsBaseUnitVariant = 1
                WHERE pv.IsDeleted = 0
                """);

            migrationBuilder.Sql("""
                UPDATE ProductVariantBomLines line
                JOIN (
                    SELECT ProductId, MIN(Id) AS VariantId
                    FROM ProductVariants
                    WHERE IsDeleted = 0 AND IsActive = 1
                    GROUP BY ProductId
                    HAVING COUNT(*) = 1
                ) single_variant ON single_variant.ProductId = line.MaterialId
                SET line.ComponentVariantId = single_variant.VariantId
                WHERE line.ComponentVariantId IS NULL
                """);

            migrationBuilder.CreateIndex(
                name: "IX_ProductVariants_BaseVariantId",
                table: "ProductVariants",
                column: "BaseVariantId");

            migrationBuilder.CreateIndex(
                name: "IX_ProductVariantBomLines_ComponentVariantId",
                table: "ProductVariantBomLines",
                column: "ComponentVariantId");

            migrationBuilder.CreateIndex(
                name: "IX_ProductAttributeValues_AttributeNameId",
                table: "ProductAttributeValues",
                column: "AttributeNameId");

            migrationBuilder.CreateIndex(
                name: "IX_ProductAttributeValues_ProductId",
                table: "ProductAttributeValues",
                column: "ProductId");

            migrationBuilder.CreateIndex(
                name: "IX_ProductAttributeValues_ProductId_AttributeName_Value",
                table: "ProductAttributeValues",
                columns: new[] { "ProductId", "AttributeName", "Value" });

            migrationBuilder.AddForeignKey(
                name: "FK_ProductVariantBomLines_ProductVariants_ComponentVariantId",
                table: "ProductVariantBomLines",
                column: "ComponentVariantId",
                principalTable: "ProductVariants",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_ProductVariants_ProductVariants_BaseVariantId",
                table: "ProductVariants",
                column: "BaseVariantId",
                principalTable: "ProductVariants",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ProductVariantBomLines_ProductVariants_ComponentVariantId",
                table: "ProductVariantBomLines");

            migrationBuilder.DropForeignKey(
                name: "FK_ProductVariants_ProductVariants_BaseVariantId",
                table: "ProductVariants");

            migrationBuilder.DropTable(name: "ProductAttributeValues");

            migrationBuilder.DropIndex(
                name: "IX_ProductVariants_BaseVariantId",
                table: "ProductVariants");

            migrationBuilder.DropIndex(
                name: "IX_ProductVariantBomLines_ComponentVariantId",
                table: "ProductVariantBomLines");

            migrationBuilder.DropColumn(
                name: "BaseVariantId",
                table: "ProductVariants");

            migrationBuilder.DropColumn(
                name: "ConversionRate",
                table: "ProductVariants");

            migrationBuilder.DropColumn(
                name: "IsAutoGeneratedSku",
                table: "ProductVariants");

            migrationBuilder.DropColumn(
                name: "IsBaseUnitVariant",
                table: "ProductVariants");

            migrationBuilder.DropColumn(
                name: "UnitName",
                table: "ProductVariants");

            migrationBuilder.DropColumn(
                name: "ComponentVariantId",
                table: "ProductVariantBomLines");
        }
    }
}
