<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HuongVanTra.Core\HuongVanTra.Core.csproj" />
    <ProjectReference Include="..\HuongVanTra.Infrastructure\HuongVanTra.Infrastructure.csproj" />
  </ItemGroup>

</Project>
