-- =============================================================================
-- Dụng cụ trà: thêm NL Piece (mua về) + BOM thành phẩm = NL x1 + BB-TEM-HVT x1
-- Ví dụ: HVT-XUC-TRE ← NL-XUC-TRE + BB-TEM-HVT
-- An toàn chạy lại (idempotent theo SkuCode cố định).
--
-- Windows PowerShell (tránh mất dấu):
--   docker cp backend/huongvantra_backend/Scripts/fix-tool-product-boms-with-nl.sql hvt-mysql:/tmp/fix-tool-boms.sql
--   docker exec hvt-mysql mysql -uhvtuser -phvtpass123 --default-character-set=utf8mb4 -e "source /tmp/fix-tool-boms.sql"
-- =============================================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET @NOW = UTC_TIMESTAMP(6);

USE `hvt_product_db`;

SET @CAT_NL = 9206; -- Nguyen lieu san xuat
SET @TEM_VARIANT = (SELECT Id FROM ProductVariants WHERE SkuCode = 'BB-TEM-HVT' AND IsDeleted = 0 LIMIT 1);
SET @TEM_PRODUCT = (SELECT ProductId FROM ProductVariants WHERE Id = @TEM_VARIANT LIMIT 1);

-- Mapping: finished SKU → NL SKU / name / cost
DROP TEMPORARY TABLE IF EXISTS tmp_tool_nl;
CREATE TEMPORARY TABLE tmp_tool_nl (
  FinishedSku VARCHAR(50) PRIMARY KEY,
  NlSku VARCHAR(50) NOT NULL,
  NlName VARCHAR(255) NOT NULL,
  CostPrice DECIMAL(18,2) NOT NULL,
  MinStock INT NOT NULL,
  ProductId CHAR(36) NOT NULL,
  VariantId CHAR(36) NOT NULL
);

INSERT INTO tmp_tool_nl (FinishedSku, NlSku, NlName, CostPrice, MinStock, ProductId, VariantId) VALUES
  ('HVT-XUC-TRE',        'NL-XUC-TRE',        'Xúc trà tre (NL)',              20000,  50, 'b1000005-0000-4000-8000-000000000005', 'b2000005-0000-4000-8000-000000000005'),
  ('HVT-XUC-DONG-GO',    'NL-XUC-DONG-GO',    'Xúc trà đồng cán gỗ (NL)',      25000,  50, 'b1000006-0000-4000-8000-000000000006', 'b2000006-0000-4000-8000-000000000006'),
  ('HVT-XUC-GO-NAU',     'NL-XUC-GO-NAU',     'Xúc trà gỗ nâu (NL)',           45000,  50, 'b1000007-0000-4000-8000-000000000007', 'b2000007-0000-4000-8000-000000000007'),
  ('HVT-XUC-VANG-DEN',   'NL-XUC-VANG-DEN',   'Xúc trà vàng chuôi đen (NL)',  120000,  30, 'b1000008-0000-4000-8000-000000000008', 'b2000008-0000-4000-8000-000000000008'),
  ('HVT-XUC-CHUOI-RONG', 'NL-XUC-CHUOI-RONG', 'Xúc trà chuôi rồng (NL)',       55000,  30, 'b1000009-0000-4000-8000-000000000009', 'b2000009-0000-4000-8000-000000000009'),
  ('HVT-TONG-THUY-TINH', 'NL-TONG-THUY-TINH', 'Tống thủy tinh trong (NL)',    250000,  20, 'b1000010-0000-4000-8000-000000000010', 'b2000010-0000-4000-8000-000000000010'),
  ('HVT-TONG-NAU-DO',    'NL-TONG-NAU-DO',    'Tống nâu đỏ (NL)',              60000,  20, 'b1000011-0000-4000-8000-000000000011', 'b2000011-0000-4000-8000-000000000011'),
  ('HVT-TONG-QUAI-GO',   'NL-TONG-QUAI-GO',   'Tống quai gỗ to (NL)',         180000,  20, 'b1000012-0000-4000-8000-000000000012', 'b2000012-0000-4000-8000-000000000012');

-- Products (NL)
INSERT INTO Products
  (Id, CategoryId, Name, Origin, FlavorProfile, BrewingGuide, Description, IsActive, CreatedAt, UpdatedAt, IsDeleted, SyncedToStoreAt, BaseUnit, IsVariantParent, WeightUnit, WeightValue, ProductType, InventoryUnit)
SELECT
  t.ProductId, @CAT_NL, t.NlName, NULL, NULL, NULL,
  'Nguyên liệu dụng cụ mua về — component BOM cho thành phẩm kệ.',
  1, @NOW, @NOW, 0, NULL, 'Cái', 1, NULL, NULL, 'NGUYEN_LIEU', 'Piece'
FROM tmp_tool_nl t
WHERE NOT EXISTS (SELECT 1 FROM Products p WHERE p.Id = t.ProductId)
  AND NOT EXISTS (SELECT 1 FROM ProductVariants v WHERE v.SkuCode = t.NlSku AND v.IsDeleted = 0);

-- Nếu SKU đã tồn tại từ lần chạy trước: reuse Id thật
UPDATE tmp_tool_nl t
INNER JOIN ProductVariants v ON v.SkuCode = t.NlSku AND v.IsDeleted = 0
SET t.ProductId = v.ProductId, t.VariantId = v.Id;

-- Variants (NL) — chỉ insert khi chưa có SkuCode
INSERT INTO ProductVariants
  (Id, ProductId, SkuCode, Barcode, VariantName, OptionValuesJson, CostPrice, RetailPrice, MinStock, MaxStock,
   IsSellable, AllowRewardPoints, IsActive, ImageUrl, CreatedAt, UpdatedAt, IsDeleted, SyncedToStoreAt,
   WeightInGrams, BaseVariantId, ConversionRate, IsAutoGeneratedSku, IsBaseUnitVariant, UnitName,
   IsPurchasable, CanBeBomComponent, CanUseInCustom, CanHaveBom,
   TotalApprovedInboundQuantity, TotalApprovedInboundValue, CostBasisReconciledAt)
SELECT
  t.VariantId, t.ProductId, t.NlSku, NULL,
  CONCAT(t.NlName, ' - Cái'), '{}', t.CostPrice, 0, t.MinStock, t.MinStock * 5,
  0, 0, 1, NULL, @NOW, @NOW, 0, NULL,
  0, NULL, 1.0000, 0, 1, 'Cái',
  1, 1, 0, 0,
  0, 0, NULL
FROM tmp_tool_nl t
WHERE NOT EXISTS (SELECT 1 FROM ProductVariants v WHERE v.SkuCode = t.NlSku);

-- Refresh Ids sau insert
UPDATE tmp_tool_nl t
INNER JOIN ProductVariants v ON v.SkuCode = t.NlSku AND v.IsDeleted = 0
SET t.ProductId = v.ProductId, t.VariantId = v.Id;

UPDATE Products p
INNER JOIN tmp_tool_nl t ON t.ProductId = p.Id
SET p.IsDeleted = 0, p.IsActive = 1, p.CategoryId = @CAT_NL, p.UpdatedAt = @NOW,
    p.ProductType = 'NGUYEN_LIEU', p.InventoryUnit = 'Piece', p.BaseUnit = 'Cái', p.Name = t.NlName;

UPDATE ProductVariants v
INNER JOIN tmp_tool_nl t ON t.VariantId = v.Id
SET v.IsDeleted = 0, v.IsActive = 1, v.IsSellable = 0, v.IsPurchasable = 1,
    v.CanBeBomComponent = 1, v.CanHaveBom = 0, v.IsBaseUnitVariant = 1,
    v.UnitName = 'Cái', v.CostPrice = t.CostPrice, v.UpdatedAt = @NOW;

-- Soft-delete BOM cũ của TP dụng cụ
UPDATE ProductVariantBomLines b
INNER JOIN ProductVariants fv ON fv.Id = b.ProductVariantId
INNER JOIN tmp_tool_nl t ON t.FinishedSku = fv.SkuCode
SET b.IsDeleted = 1, b.UpdatedAt = @NOW
WHERE b.IsDeleted = 0;

-- BOM: NL x1 (operational) + TEM x1 — IsRequiredBaseComponent phải = 0
-- (flag=1 bị bom-catalog loại → bán-trước-trừ-sau không trừ NL).
INSERT INTO ProductVariantBomLines
  (ProductVariantId, MaterialId, ComponentVariantId, Quantity, IsRequiredBaseComponent, CreatedAt, UpdatedAt, IsDeleted)
SELECT fv.Id, t.ProductId, t.VariantId, 1.0000, 0, @NOW, @NOW, 0
FROM tmp_tool_nl t
INNER JOIN ProductVariants fv ON fv.SkuCode = t.FinishedSku AND fv.IsDeleted = 0
WHERE NOT EXISTS (
  SELECT 1 FROM ProductVariantBomLines x
  WHERE x.ProductVariantId = fv.Id AND x.ComponentVariantId = t.VariantId AND x.IsDeleted = 0
);

-- Heal dòng NL đã insert trước đó với flag required-base = 1
UPDATE ProductVariantBomLines b
INNER JOIN ProductVariants fv ON fv.Id = b.ProductVariantId AND fv.IsDeleted = 0
INNER JOIN ProductVariants cv ON cv.Id = b.ComponentVariantId AND cv.IsDeleted = 0
INNER JOIN tmp_tool_nl t ON t.FinishedSku = fv.SkuCode AND t.VariantId = cv.Id
SET b.IsRequiredBaseComponent = 0, b.Quantity = 1.0000, b.UpdatedAt = @NOW
WHERE b.IsDeleted = 0 AND b.IsRequiredBaseComponent = 1;

INSERT INTO ProductVariantBomLines
  (ProductVariantId, MaterialId, ComponentVariantId, Quantity, IsRequiredBaseComponent, CreatedAt, UpdatedAt, IsDeleted)
SELECT fv.Id, @TEM_PRODUCT, @TEM_VARIANT, 1.0000, 0, @NOW, @NOW, 0
FROM tmp_tool_nl t
INNER JOIN ProductVariants fv ON fv.SkuCode = t.FinishedSku AND fv.IsDeleted = 0
WHERE @TEM_VARIANT IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM ProductVariantBomLines x
    WHERE x.ProductVariantId = fv.Id AND x.ComponentVariantId = @TEM_VARIANT AND x.IsDeleted = 0
  );

SELECT fv.SkuCode AS FinishedSku, p.Name AS FinishedName, c.SkuCode AS Comp, b.Quantity, b.IsRequiredBaseComponent
FROM ProductVariantBomLines b
JOIN ProductVariants fv ON fv.Id = b.ProductVariantId
JOIN Products p ON p.Id = fv.ProductId
JOIN ProductVariants c ON c.Id = b.ComponentVariantId
WHERE b.IsDeleted = 0
  AND (fv.SkuCode LIKE 'HVT-TONG-%' OR fv.SkuCode LIKE 'HVT-XUC-%')
ORDER BY fv.SkuCode, b.IsRequiredBaseComponent DESC, c.SkuCode;

SELECT v.SkuCode, p.Name, p.CategoryId, v.CanBeBomComponent, v.IsPurchasable, v.IsSellable
FROM ProductVariants v
JOIN Products p ON p.Id = v.ProductId
WHERE v.SkuCode LIKE 'NL-XUC-%' OR v.SkuCode LIKE 'NL-TONG-%'
ORDER BY v.SkuCode;
