<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\InventoryService.Domain\InventoryService.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared_Libraries\HuongVanTra.Shared\HuongVanTra.Shared.csproj" />
  </ItemGroup>
</Project>
