using ProductService.Application.DTOs.Requests;
using ProductService.Application.Validation;
using ProductService.Domain.Enums;
using ProductService.Domain.Exceptions;
using Xunit;

namespace ProductService.Application.Tests;

public class ProductInputValidatorTests
{
    private static ProductValidationException AssertValidation(Action action)
    {
        var ex = Assert.Throws<ProductValidationException>(action);
        Assert.NotEmpty(ex.Errors);
        return ex;
    }

    private static VariantInput Variant(
        string? skuCode = "TEA-001",
        string? variantName = "Goi 100g",
        decimal costPrice = 100m,
        decimal retailPrice = 1000m,
        int? minStock = null,
        int? maxStock = null,
        bool isSellable = true,
        string? imageUrl = null,
        string? unitName = null,
        decimal? conversionRate = null,
        string? requestSkuKey = null,
        string? baseSkuCode = null,
        string? baseRequestSkuKey = null,
        bool? isBaseUnitVariant = null,
        bool? isAutoGeneratedSku = null)
    {
        return new VariantInput
        {
            SkuCode = skuCode,
            Barcode = (string?)null,
            VariantName = variantName,
            OptionValuesJson = "{}",
            CostPrice = costPrice,
            RetailPrice = retailPrice,
            MinStock = minStock,
            MaxStock = maxStock,
            IsSellable = isSellable,
            AllowRewardPoints = true,
            IsActive = true,
            ImageUrl = imageUrl,
            Units = Array.Empty<object>(),
            UnitName = unitName,
            ConversionRate = conversionRate,
            RequestSkuKey = requestSkuKey,
            BaseSkuCode = baseSkuCode,
            BaseRequestSkuKey = baseRequestSkuKey,
            IsBaseUnitVariant = isBaseUnitVariant,
            IsAutoGeneratedSku = isAutoGeneratedSku,
        };
    }

    private static CreateProductRequest ProductWithSkuPrices(params ProductVariantRequest[] variants) =>
        new(
            1,
            "Tra Test",
            null,
            null,
            null,
            null,
            "Goi",
            "Piece",
            null,
            null,
            true,
            ProductType.THANH_PHAM.ToString(),
            [],
            [],
            variants.ToList(),
            null);

    private static ProductVariantRequest SkuPriceVariant(
        string skuCode,
        decimal retailPrice,
        decimal conversionRate,
        bool isBase,
        string requestSkuKey,
        string? baseRequestSkuKey = null) =>
        new(
            skuCode,
            requestSkuKey,
            null,
            $"Tra Test - {skuCode}",
            "{}",
            0m,
            retailPrice,
            0,
            null,
            true,
            true,
            true,
            null,
            [],
            [],
            "Goi",
            conversionRate,
            null,
            null,
            baseRequestSkuKey,
            isBase,
            true);

    [Fact]
    public void ValidatePagination_RejectsPageSizeOver100()
    {
        var ex = AssertValidation(() => ProductInputValidator.ValidatePagination(1, 101));
        Assert.Contains(ex.Errors, e => e.Contains("PageSize"));
    }

    [Fact]
    public void ValidatePagination_AcceptsPageSize100()
    {
        ProductInputValidator.ValidatePagination(1, 100);
    }

    [Fact]
    public void ValidateVariants_RejectsInvalidSkuCode()
    {
        var ex = AssertValidation(() => ProductInputValidator.ValidateVariants([Variant(skuCode: "ab")]));

        Assert.Contains(ex.Errors, e => e.Contains("SKU"));
    }

    [Theory]
    [InlineData("TEA-001")]
    [InlineData("CF_500G")]
    [InlineData("ABC123")]
    public void ValidateVariants_AcceptsValidSkuCode(string code)
    {
        var result = ProductInputValidator.ValidateVariants([Variant(skuCode: code)]);

        Assert.Equal(code, result[0].SkuCode);
    }

    [Fact]
    public void ValidateVariants_UppercasesSkuCode()
    {
        var result = ProductInputValidator.ValidateVariants([Variant(skuCode: "tea-001")]);

        Assert.Equal("TEA-001", result[0].SkuCode);
    }

    [Fact]
    public void ValidateVariants_RejectsZeroRetailPriceForSellableSku()
    {
        var ex = AssertValidation(() => ProductInputValidator.ValidateVariants([Variant(retailPrice: 0m)]));

        Assert.NotEmpty(ex.Errors);
    }

    [Fact]
    public void ValidateVariants_RejectsPriceOverMax()
    {
        var ex = AssertValidation(() => ProductInputValidator.ValidateVariants([Variant(retailPrice: 1_000_000_001m)]));

        Assert.Contains(ex.Errors, e => e.Contains("1,000,000,000"));
    }

    [Fact]
    public void ValidateVariants_RejectsMoreThanTwoDecimalPlaces()
    {
        var ex = AssertValidation(() => ProductInputValidator.ValidateVariants([Variant(retailPrice: 100.123m)]));

        Assert.NotEmpty(ex.Errors);
    }

    [Fact]
    public void ValidateVariants_AcceptsTwoDecimalPlaces()
    {
        var result = ProductInputValidator.ValidateVariants([Variant(retailPrice: 100.25m)]);

        Assert.Equal(100.25m, result[0].RetailPrice);
    }

    [Fact]
    public void ValidateVariants_AcceptsSkuUnitMetadata()
    {
        var result = ProductInputValidator.ValidateVariants([
            Variant(
                skuCode: "TRA-NHAI-HOP",
                variantName: "Tra Nhai - Hop",
                unitName: "Hop",
                conversionRate: 1m,
                requestSkuKey: "sku-base",
                isBaseUnitVariant: true,
                isAutoGeneratedSku: true),
            Variant(
                skuCode: "TRA-NHAI-THUNG-10",
                variantName: "Tra Nhai - Thung",
                unitName: "Thung",
                conversionRate: 10m,
                baseRequestSkuKey: "sku-base",
                isBaseUnitVariant: false,
                isAutoGeneratedSku: true),
        ]);

        Assert.Equal("Hop", result[0].UnitName);
        Assert.Equal(1m, result[0].ConversionRate);
        Assert.True(result[0].IsBaseUnitVariant);
        Assert.Equal("sku-base", result[0].RequestSkuKey);
        Assert.Equal("Thung", result[1].UnitName);
        Assert.Equal(10m, result[1].ConversionRate);
        Assert.Equal("sku-base", result[1].BaseRequestSkuKey);
        Assert.True(result[1].IsAutoGeneratedSku);
    }

    [Fact]
    public void ValidateVariants_RejectsInvalidSkuConversionRate()
    {
        var ex = AssertValidation(() => ProductInputValidator.ValidateVariants([
            Variant(conversionRate: 0m),
        ]));

        Assert.Contains(ex.Errors, e => e.Contains("Ty le quy doi SKU"));
    }

    [Fact]
    public void ValidateVariants_RejectsFractionalSkuConversionRate()
    {
        var ex = AssertValidation(() => ProductInputValidator.ValidateVariants([
            Variant(conversionRate: 10.5m),
        ]));

        Assert.Contains(ex.Errors, e => e.Contains("so nguyen"));
    }

    [Fact]
    public void ValidateDerivedSkuRetailPrices_AcceptsBasePriceTimesConversion()
    {
        var product = ProductWithSkuPrices(
            SkuPriceVariant("TRA-GOI", 20_000m, 1m, true, "sku-base"),
            SkuPriceVariant("TRA-THUNG-10", 200_000m, 10m, false, "sku-thung", "sku-base"));

        ProductInputValidator.ValidateDerivedSkuRetailPrices(product);
    }

    [Fact]
    public void ValidateDerivedSkuRetailPrices_AcceptsUpdatedConversionPrice()
    {
        var product = ProductWithSkuPrices(
            SkuPriceVariant("TRA-GOI", 20_000m, 1m, true, "sku-base"),
            SkuPriceVariant("TRA-THUNG-15", 300_000m, 15m, false, "sku-thung", "sku-base"));

        ProductInputValidator.ValidateDerivedSkuRetailPrices(product);
    }

    [Fact]
    public void ValidateDerivedSkuRetailPrices_AcceptsUpdatedBasePriceForAllDerivedSkus()
    {
        var product = ProductWithSkuPrices(
            SkuPriceVariant("TRA-GOI", 25_000m, 1m, true, "sku-base"),
            SkuPriceVariant("TRA-THUNG-15", 375_000m, 15m, false, "sku-thung", "sku-base"),
            SkuPriceVariant("TRA-KIEN-50", 1_250_000m, 50m, false, "sku-kien", "sku-base"));

        ProductInputValidator.ValidateDerivedSkuRetailPrices(product);
    }

    [Fact]
    public void ValidateDerivedSkuRetailPrices_RejectsTamperedDerivedPrice()
    {
        var product = ProductWithSkuPrices(
            SkuPriceVariant("TRA-GOI", 20_000m, 1m, true, "sku-base"),
            SkuPriceVariant("TRA-THUNG-15", 200_000m, 15m, false, "sku-thung", "sku-base"));

        var ex = AssertValidation(() => ProductInputValidator.ValidateDerivedSkuRetailPrices(product));

        Assert.Contains(ex.Errors, e => e.Contains("SKU quy đổi"));
    }

    [Fact]
    public void ValidateAttributes_AcceptsVietnameseCustomAttribute()
    {
        var attributes = ProductInputValidator.ValidateAttributes([
            new ProductAttributeValueRequest(null, "  Cấp   độ trà  ", " Đặc biệt "),
        ]);

        Assert.Single(attributes);
        Assert.Equal("Cấp độ trà", attributes[0].AttributeName);
        Assert.Equal("Đặc biệt", attributes[0].Value);
    }

    [Fact]
    public void ValidateAttributes_RejectsDuplicateNormalizedNames()
    {
        var ex = AssertValidation(() => ProductInputValidator.ValidateAttributes([
            new ProductAttributeValueRequest(null, "Hương vị", "Nhài"),
            new ProductAttributeValueRequest(null, "  hương   vị  ", "Sen"),
        ]));

        Assert.Contains(ex.Errors, e => e.Contains("đã được sử dụng"));
    }

    [Fact]
    public void ValidateAttributes_RejectsSelectedNameWithoutValue()
    {
        var ex = AssertValidation(() => ProductInputValidator.ValidateAttributes([
            new ProductAttributeValueRequest(null, "Xuất xứ", ""),
        ]));

        Assert.Contains(ex.Errors, e => e.Contains("Vui lòng nhập giá trị thuộc tính"));
    }

    [Fact]
    public void ValidateAttributes_RejectsValueWithoutName()
    {
        var ex = AssertValidation(() => ProductInputValidator.ValidateAttributes([
            new ProductAttributeValueRequest(null, "", "Nhài"),
        ]));

        Assert.Contains(ex.Errors, e => e.Contains("thiếu tên thuộc tính"));
    }

    [Theory]
    [InlineData(1)]
    [InlineData(10)]
    [InlineData(100)]
    public void BomUnitRules_AcceptsPositiveIntegerQuantity(decimal quantity)
    {
        Assert.True(BomUnitRules.IsIntegerQuantity(quantity));
    }

    [Theory]
    [InlineData(0.999)]
    [InlineData(1.001)]
    [InlineData(10.5)]
    public void BomUnitRules_RejectsFractionalQuantity(decimal quantity)
    {
        Assert.False(BomUnitRules.IsIntegerQuantity(quantity));
    }

    [Fact]
    public void ValidateVariants_RejectsInvalidImageUrl()
    {
        var ex = AssertValidation(() => ProductInputValidator.ValidateVariants([Variant(imageUrl: "ftp://bad.com/a.jpg")]));

        Assert.Contains(ex.Errors, e => e.Contains("URL"));
    }

    [Theory]
    [InlineData("http://example.com/a.jpg")]
    [InlineData("https://cdn.example.com/tea.png")]
    public void ValidateVariants_AcceptsHttpHttpsImageUrl(string url)
    {
        var result = ProductInputValidator.ValidateVariants([Variant(imageUrl: url)]);

        Assert.Equal(url, result[0].ImageUrl);
    }

    [Fact]
    public void ValidateVariants_RejectsInvalidStockRange()
    {
        var ex = AssertValidation(() => ProductInputValidator.ValidateVariants([Variant(minStock: 10, maxStock: 5)]));

        Assert.NotEmpty(ex.Errors);
    }

    [Fact]
    public void ValidateVariants_RejectsDuplicateSkuCodes()
    {
        var ex = AssertValidation(() => ProductInputValidator.ValidateVariants([
            Variant(skuCode: "TEA-001"),
            Variant(skuCode: "tea-001"),
        ]));

        Assert.Contains(ex.Errors, e => e.Contains("SKU"));
    }

    [Fact]
    public void ValidateVariants_ReturnsMultipleErrors()
    {
        var ex = AssertValidation(() => ProductInputValidator.ValidateVariants([
            Variant(skuCode: "x", variantName: "", retailPrice: 0m, imageUrl: "not-a-url"),
        ]));

        Assert.True(ex.Errors.Count >= 3);
    }

    [Fact]
    public void ValidateCategory_RejectsEmptyName()
    {
        var ex = AssertValidation(() => ProductInputValidator.ValidateCategory("", null, null));

        Assert.Contains(ex.Errors, e => e.Contains("danh"));
    }

    [Fact]
    public void ValidateProduct_InfersGramInventoryUnitFromKg()
    {
        var result = ProductInputValidator.ValidateProduct(
            1,
            "Tra nhai",
            null,
            null,
            null,
            null,
            baseUnitValue: "kg",
            weightValue: null,
            weightUnitValue: null);

        Assert.Equal(InventoryUnit.Gram, result.InventoryUnit);
    }

    [Fact]
    public void InventoryUnitConverter_ConvertsKgToIntegerGrams()
    {
        var quantity = InventoryUnitConverter.NormalizeQuantity(0.48m, InventoryUnit.Gram, "kg");

        Assert.Equal(480, quantity);
    }

    [Fact]
    public void InventoryUnitConverter_RejectsDecimalPieces()
    {
        var ex = Assert.Throws<ProductValidationException>(() =>
            InventoryUnitConverter.NormalizeQuantity(1.5m, InventoryUnit.Piece, "cái"));

        Assert.NotEmpty(ex.Errors);
    }
}

public sealed class VariantInput
{
    public string? SkuCode { get; set; }
    public string? Barcode { get; set; }
    public string? VariantName { get; set; }
    public string? OptionValuesJson { get; set; }
    public decimal CostPrice { get; set; }
    public decimal RetailPrice { get; set; }
    public int? MinStock { get; set; }
    public int? MaxStock { get; set; }
    public bool IsSellable { get; set; }
    public bool AllowRewardPoints { get; set; }
    public bool IsActive { get; set; }
    public string? ImageUrl { get; set; }
    public object[] Units { get; set; } = [];
    public string? UnitName { get; set; }
    public decimal? ConversionRate { get; set; }
    public Guid? BaseVariantId { get; set; }
    public string? BaseSkuCode { get; set; }
    public string? RequestSkuKey { get; set; }
    public string? BaseRequestSkuKey { get; set; }
    public bool? IsBaseUnitVariant { get; set; }
    public bool? IsAutoGeneratedSku { get; set; }
}
